/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.mailchannels.model.DkimSetting;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * CheckDomainBody
 */
@JsonPropertyOrder({
  CheckDomainBody.JSON_PROPERTY_DKIM_SETTINGS,
  CheckDomainBody.JSON_PROPERTY_DOMAIN,
  CheckDomainBody.JSON_PROPERTY_ENVELOPE_FROM_DOMAIN,
  CheckDomainBody.JSON_PROPERTY_SENDER_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class CheckDomainBody {
  public static final String JSON_PROPERTY_DKIM_SETTINGS = "dkim_settings";
  @javax.annotation.Nullable
  private List<DkimSetting> dkimSettings = new ArrayList<>();

  public static final String JSON_PROPERTY_DOMAIN = "domain";
  @javax.annotation.Nonnull
  private String domain;

  public static final String JSON_PROPERTY_ENVELOPE_FROM_DOMAIN = "envelope_from_domain";
  @javax.annotation.Nullable
  private String envelopeFromDomain;

  public static final String JSON_PROPERTY_SENDER_ID = "sender_id";
  @javax.annotation.Nullable
  private String senderId;

  public CheckDomainBody() { 
  }

  public CheckDomainBody dkimSettings(@javax.annotation.Nullable List<DkimSetting> dkimSettings) {
    this.dkimSettings = dkimSettings;
    return this;
  }

  public CheckDomainBody addDkimSettingsItem(DkimSetting dkimSettingsItem) {
    if (this.dkimSettings == null) {
      this.dkimSettings = new ArrayList<>();
    }
    this.dkimSettings.add(dkimSettingsItem);
    return this;
  }

  /**
   * Each item may include DKIM domain, selector and private key. Up to 10 items are allowed. The absence or presence of these fields affects how DKIM settings are validated: 1. If dkim_domain, dkim_selector, and dkim_private_key are all present, verify using the provided domain, selector, and key. 2. If dkim_domain and dkim_selector are present, use the stored private key for the given domain and selector. 3. If only dkim_domain is present, use all stored keys for the given domain. 4. If none are present, use all stored keys for the domain provided in the &#x60;domain&#x60; field of the request. 5. If dkim_private_key is present, dkim_selector must be present. 6. If dkim_selector is present and dkim_domain is not, the domain will be taken from the &#x60;domain&#x60; field of the request. 
   * @return dkimSettings
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DKIM_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<DkimSetting> getDkimSettings() {
    return dkimSettings;
  }


  @JsonProperty(value = JSON_PROPERTY_DKIM_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDkimSettings(@javax.annotation.Nullable List<DkimSetting> dkimSettings) {
    this.dkimSettings = dkimSettings;
  }


  public CheckDomainBody domain(@javax.annotation.Nonnull String domain) {
    this.domain = domain;
    return this;
  }

  /**
   * Domain used for sending emails. If dkim_settings are not provided, or dkim_settings are provided with no dkim_domain, the stored dkim settings for this domain will be used. 
   * @return domain
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DOMAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDomain() {
    return domain;
  }


  @JsonProperty(value = JSON_PROPERTY_DOMAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDomain(@javax.annotation.Nonnull String domain) {
    this.domain = domain;
  }


  public CheckDomainBody envelopeFromDomain(@javax.annotation.Nullable String envelopeFromDomain) {
    this.envelopeFromDomain = envelopeFromDomain;
    return this;
  }

  /**
   * Optional envelope-from domain. During message delivery, SPF and Domain Lockdown verification are evaluated  against the envelope sender domain. If your envelope-from domain differs from the domain used for sending messages, provide it here to ensure both checks are run against the correct domain. Otherwise, SPF or Domain Lockdown failures may cause message delivery to fail. 
   * @return envelopeFromDomain
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENVELOPE_FROM_DOMAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEnvelopeFromDomain() {
    return envelopeFromDomain;
  }


  @JsonProperty(value = JSON_PROPERTY_ENVELOPE_FROM_DOMAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnvelopeFromDomain(@javax.annotation.Nullable String envelopeFromDomain) {
    this.envelopeFromDomain = envelopeFromDomain;
  }


  public CheckDomainBody senderId(@javax.annotation.Nullable String senderId) {
    this.senderId = senderId;
    return this;
  }

  /**
   * Used exclusively for [Domain Lockdown](https://support.mailchannels.com/hc/en-us/articles/16918954360845-Secure-your-domain-name-against-spoofing-with-Domain-Lockdown) verification. If you&#39;re not using &#x60;senderid&#x60; to associate your domain with your account, you can disregard this field. The corresponding value is included in the X-MailChannels-SenderId header of emails sent via MailChannels. 
   * @return senderId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SENDER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSenderId() {
    return senderId;
  }


  @JsonProperty(value = JSON_PROPERTY_SENDER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSenderId(@javax.annotation.Nullable String senderId) {
    this.senderId = senderId;
  }


  /**
   * Return true if this CheckDomainBody object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckDomainBody checkDomainBody = (CheckDomainBody) o;
    return Objects.equals(this.dkimSettings, checkDomainBody.dkimSettings) &&
        Objects.equals(this.domain, checkDomainBody.domain) &&
        Objects.equals(this.envelopeFromDomain, checkDomainBody.envelopeFromDomain) &&
        Objects.equals(this.senderId, checkDomainBody.senderId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dkimSettings, domain, envelopeFromDomain, senderId);
  }

  @Override
  public String toString() {
    return "CheckDomainBody { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `dkim_settings` to the URL query string
    if (getDkimSettings() != null) {
      for (int i = 0; i < getDkimSettings().size(); i++) {
        if (getDkimSettings().get(i) != null) {
          joiner.add(getDkimSettings().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdkim_settings%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `domain` to the URL query string
    if (getDomain() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdomain%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDomain()))));
    }

    // add `envelope_from_domain` to the URL query string
    if (getEnvelopeFromDomain() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%senvelope_from_domain%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEnvelopeFromDomain()))));
    }

    // add `sender_id` to the URL query string
    if (getSenderId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssender_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSenderId()))));
    }

    return joiner.toString();
  }
}

