/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.mailchannels.model.DkimResult;
import com.mailchannels.model.LockdownResult;
import com.mailchannels.model.SenderDomainResult;
import com.mailchannels.model.SpfResult;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * CheckResults
 */
@JsonPropertyOrder({
  CheckResults.JSON_PROPERTY_DKIM,
  CheckResults.JSON_PROPERTY_DOMAIN_LOCKDOWN,
  CheckResults.JSON_PROPERTY_SENDER_DOMAIN,
  CheckResults.JSON_PROPERTY_SPF
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class CheckResults {
  public static final String JSON_PROPERTY_DKIM = "dkim";
  @javax.annotation.Nullable
  private List<DkimResult> dkim = new ArrayList<>();

  public static final String JSON_PROPERTY_DOMAIN_LOCKDOWN = "domain_lockdown";
  @javax.annotation.Nullable
  private LockdownResult domainLockdown;

  public static final String JSON_PROPERTY_SENDER_DOMAIN = "sender_domain";
  @javax.annotation.Nullable
  private SenderDomainResult senderDomain;

  public static final String JSON_PROPERTY_SPF = "spf";
  @javax.annotation.Nullable
  private SpfResult spf;

  public CheckResults() { 
  }

  public CheckResults dkim(@javax.annotation.Nullable List<DkimResult> dkim) {
    this.dkim = dkim;
    return this;
  }

  public CheckResults addDkimItem(DkimResult dkimItem) {
    if (this.dkim == null) {
      this.dkim = new ArrayList<>();
    }
    this.dkim.add(dkimItem);
    return this;
  }

  /**
   * Get dkim
   * @return dkim
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DKIM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<DkimResult> getDkim() {
    return dkim;
  }


  @JsonProperty(value = JSON_PROPERTY_DKIM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDkim(@javax.annotation.Nullable List<DkimResult> dkim) {
    this.dkim = dkim;
  }


  public CheckResults domainLockdown(@javax.annotation.Nullable LockdownResult domainLockdown) {
    this.domainLockdown = domainLockdown;
    return this;
  }

  /**
   * Get domainLockdown
   * @return domainLockdown
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DOMAIN_LOCKDOWN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public LockdownResult getDomainLockdown() {
    return domainLockdown;
  }


  @JsonProperty(value = JSON_PROPERTY_DOMAIN_LOCKDOWN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDomainLockdown(@javax.annotation.Nullable LockdownResult domainLockdown) {
    this.domainLockdown = domainLockdown;
  }


  public CheckResults senderDomain(@javax.annotation.Nullable SenderDomainResult senderDomain) {
    this.senderDomain = senderDomain;
    return this;
  }

  /**
   * Get senderDomain
   * @return senderDomain
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SENDER_DOMAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SenderDomainResult getSenderDomain() {
    return senderDomain;
  }


  @JsonProperty(value = JSON_PROPERTY_SENDER_DOMAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSenderDomain(@javax.annotation.Nullable SenderDomainResult senderDomain) {
    this.senderDomain = senderDomain;
  }


  public CheckResults spf(@javax.annotation.Nullable SpfResult spf) {
    this.spf = spf;
    return this;
  }

  /**
   * Get spf
   * @return spf
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SPF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SpfResult getSpf() {
    return spf;
  }


  @JsonProperty(value = JSON_PROPERTY_SPF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpf(@javax.annotation.Nullable SpfResult spf) {
    this.spf = spf;
  }


  /**
   * Return true if this CheckResults object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckResults checkResults = (CheckResults) o;
    return Objects.equals(this.dkim, checkResults.dkim) &&
        Objects.equals(this.domainLockdown, checkResults.domainLockdown) &&
        Objects.equals(this.senderDomain, checkResults.senderDomain) &&
        Objects.equals(this.spf, checkResults.spf);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dkim, domainLockdown, senderDomain, spf);
  }

  @Override
  public String toString() {
    return "CheckResults { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `dkim` to the URL query string
    if (getDkim() != null) {
      for (int i = 0; i < getDkim().size(); i++) {
        if (getDkim().get(i) != null) {
          joiner.add(getDkim().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdkim%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `domain_lockdown` to the URL query string
    if (getDomainLockdown() != null) {
      joiner.add(getDomainLockdown().toUrlQueryString(prefix + "domain_lockdown" + suffix));
    }

    // add `sender_domain` to the URL query string
    if (getSenderDomain() != null) {
      joiner.add(getSenderDomain().toUrlQueryString(prefix + "sender_domain" + suffix));
    }

    // add `spf` to the URL query string
    if (getSpf() != null) {
      joiner.add(getSpf().toUrlQueryString(prefix + "spf" + suffix));
    }

    return joiner.toString();
  }
}

