/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.mailchannels.model.CustomTrackingDomain;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * CustomTrackingDomainListResponse
 */
@JsonPropertyOrder({
  CustomTrackingDomainListResponse.JSON_PROPERTY_CUSTOM_TRACKING_DOMAINS,
  CustomTrackingDomainListResponse.JSON_PROPERTY_TOTAL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class CustomTrackingDomainListResponse {
  public static final String JSON_PROPERTY_CUSTOM_TRACKING_DOMAINS = "custom_tracking_domains";
  @javax.annotation.Nonnull
  private List<CustomTrackingDomain> customTrackingDomains = new ArrayList<>();

  public static final String JSON_PROPERTY_TOTAL = "total";
  @javax.annotation.Nonnull
  private Integer total;

  public CustomTrackingDomainListResponse() { 
  }

  public CustomTrackingDomainListResponse customTrackingDomains(@javax.annotation.Nonnull List<CustomTrackingDomain> customTrackingDomains) {
    this.customTrackingDomains = customTrackingDomains;
    return this;
  }

  public CustomTrackingDomainListResponse addCustomTrackingDomainsItem(CustomTrackingDomain customTrackingDomainsItem) {
    if (this.customTrackingDomains == null) {
      this.customTrackingDomains = new ArrayList<>();
    }
    this.customTrackingDomains.add(customTrackingDomainsItem);
    return this;
  }

  /**
   * List of custom tracking domains matching the filter criteria
   * @return customTrackingDomains
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_TRACKING_DOMAINS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<CustomTrackingDomain> getCustomTrackingDomains() {
    return customTrackingDomains;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_TRACKING_DOMAINS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCustomTrackingDomains(@javax.annotation.Nonnull List<CustomTrackingDomain> customTrackingDomains) {
    this.customTrackingDomains = customTrackingDomains;
  }


  public CustomTrackingDomainListResponse total(@javax.annotation.Nonnull Integer total) {
    this.total = total;
    return this;
  }

  /**
   * Total number of custom tracking domains
   * @return total
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getTotal() {
    return total;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotal(@javax.annotation.Nonnull Integer total) {
    this.total = total;
  }


  /**
   * Return true if this CustomTrackingDomainListResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomTrackingDomainListResponse customTrackingDomainListResponse = (CustomTrackingDomainListResponse) o;
    return Objects.equals(this.customTrackingDomains, customTrackingDomainListResponse.customTrackingDomains) &&
        Objects.equals(this.total, customTrackingDomainListResponse.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customTrackingDomains, total);
  }

  @Override
  public String toString() {
    return "CustomTrackingDomainListResponse { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `custom_tracking_domains` to the URL query string
    if (getCustomTrackingDomains() != null) {
      for (int i = 0; i < getCustomTrackingDomains().size(); i++) {
        if (getCustomTrackingDomains().get(i) != null) {
          joiner.add(getCustomTrackingDomains().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%scustom_tracking_domains%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `total` to the URL query string
    if (getTotal() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotal%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotal()))));
    }

    return joiner.toString();
  }
}

