/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * CustomTrackingDomain
 */
@JsonPropertyOrder({
  CustomTrackingDomain.JSON_PROPERTY_CREATED_AT,
  CustomTrackingDomain.JSON_PROPERTY_HOSTNAME,
  CustomTrackingDomain.JSON_PROPERTY_NAME,
  CustomTrackingDomain.JSON_PROPERTY_SCOPE,
  CustomTrackingDomain.JSON_PROPERTY_STATUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class CustomTrackingDomain {
  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_HOSTNAME = "hostname";
  @javax.annotation.Nonnull
  private String hostname;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  /**
   * The event type this domain handles
   */
  public enum ScopeEnum {
    CLICK(String.valueOf("click")),
    
    OPEN(String.valueOf("open")),
    
    UNSUBSCRIBE(String.valueOf("unsubscribe"));

    private String value;

    ScopeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ScopeEnum fromValue(String value) {
      for (ScopeEnum b : ScopeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SCOPE = "scope";
  @javax.annotation.Nonnull
  private ScopeEnum scope;

  /**
   * Current status of the custom tracking domain
   */
  public enum StatusEnum {
    ACTIVE(String.valueOf("active")),
    
    DISABLED(String.valueOf("disabled"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private StatusEnum status;

  public CustomTrackingDomain() { 
  }

  public CustomTrackingDomain createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * ISO 8601 timestamp when the domain was registered
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public CustomTrackingDomain hostname(@javax.annotation.Nonnull String hostname) {
    this.hostname = hostname;
    return this;
  }

  /**
   * The registered domain hostname
   * @return hostname
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HOSTNAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getHostname() {
    return hostname;
  }


  @JsonProperty(value = JSON_PROPERTY_HOSTNAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHostname(@javax.annotation.Nonnull String hostname) {
    this.hostname = hostname;
  }


  public CustomTrackingDomain name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The label for this custom tracking domain
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public CustomTrackingDomain scope(@javax.annotation.Nonnull ScopeEnum scope) {
    this.scope = scope;
    return this;
  }

  /**
   * The event type this domain handles
   * @return scope
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SCOPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ScopeEnum getScope() {
    return scope;
  }


  @JsonProperty(value = JSON_PROPERTY_SCOPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setScope(@javax.annotation.Nonnull ScopeEnum scope) {
    this.scope = scope;
  }


  public CustomTrackingDomain status(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Current status of the custom tracking domain
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  /**
   * Return true if this CustomTrackingDomain object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomTrackingDomain customTrackingDomain = (CustomTrackingDomain) o;
    return Objects.equals(this.createdAt, customTrackingDomain.createdAt) &&
        Objects.equals(this.hostname, customTrackingDomain.hostname) &&
        Objects.equals(this.name, customTrackingDomain.name) &&
        Objects.equals(this.scope, customTrackingDomain.scope) &&
        Objects.equals(this.status, customTrackingDomain.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, hostname, name, scope, status);
  }

  @Override
  public String toString() {
    return "CustomTrackingDomain { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `hostname` to the URL query string
    if (getHostname() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shostname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHostname()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `scope` to the URL query string
    if (getScope() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sscope%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getScope()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    return joiner.toString();
  }
}

