/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.mailchannels.model.DKIMKeyInfo;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * DKIMKeyList
 */
@JsonPropertyOrder({
  DKIMKeyList.JSON_PROPERTY_KEYS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class DKIMKeyList {
  public static final String JSON_PROPERTY_KEYS = "keys";
  @javax.annotation.Nonnull
  private List<DKIMKeyInfo> keys = new ArrayList<>();

  public DKIMKeyList() { 
  }

  public DKIMKeyList keys(@javax.annotation.Nonnull List<DKIMKeyInfo> keys) {
    this.keys = keys;
    return this;
  }

  public DKIMKeyList addKeysItem(DKIMKeyInfo keysItem) {
    if (this.keys == null) {
      this.keys = new ArrayList<>();
    }
    this.keys.add(keysItem);
    return this;
  }

  /**
   * List of keys matching the filter. Empty if no keys match the filter. 
   * @return keys
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<DKIMKeyInfo> getKeys() {
    return keys;
  }


  @JsonProperty(value = JSON_PROPERTY_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKeys(@javax.annotation.Nonnull List<DKIMKeyInfo> keys) {
    this.keys = keys;
  }


  /**
   * Return true if this DKIMKeyList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DKIMKeyList dkIMKeyList = (DKIMKeyList) o;
    return Objects.equals(this.keys, dkIMKeyList.keys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keys);
  }

  @Override
  public String toString() {
    return "DKIMKeyList { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `keys` to the URL query string
    if (getKeys() != null) {
      for (int i = 0; i < getKeys().size(); i++) {
        if (getKeys().get(i) != null) {
          joiner.add(getKeys().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%skeys%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

