/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * DKIMKeyPairCreateRequest
 */
@JsonPropertyOrder({
  DKIMKeyPairCreateRequest.JSON_PROPERTY_ALGORITHM,
  DKIMKeyPairCreateRequest.JSON_PROPERTY_KEY_LENGTH,
  DKIMKeyPairCreateRequest.JSON_PROPERTY_SELECTOR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class DKIMKeyPairCreateRequest {
  /**
   * Algorithm used for the new key pair Currently, only RSA is supported. 
   */
  public enum AlgorithmEnum {
    RSA(String.valueOf("rsa"));

    private String value;

    AlgorithmEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AlgorithmEnum fromValue(String value) {
      for (AlgorithmEnum b : AlgorithmEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ALGORITHM = "algorithm";
  @javax.annotation.Nullable
  private AlgorithmEnum algorithm = AlgorithmEnum.RSA;

  public static final String JSON_PROPERTY_KEY_LENGTH = "key_length";
  @javax.annotation.Nullable
  private Integer keyLength = 2048;

  public static final String JSON_PROPERTY_SELECTOR = "selector";
  @javax.annotation.Nonnull
  private String selector;

  public DKIMKeyPairCreateRequest() { 
  }

  public DKIMKeyPairCreateRequest algorithm(@javax.annotation.Nullable AlgorithmEnum algorithm) {
    this.algorithm = algorithm;
    return this;
  }

  /**
   * Algorithm used for the new key pair Currently, only RSA is supported. 
   * @return algorithm
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALGORITHM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AlgorithmEnum getAlgorithm() {
    return algorithm;
  }


  @JsonProperty(value = JSON_PROPERTY_ALGORITHM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlgorithm(@javax.annotation.Nullable AlgorithmEnum algorithm) {
    this.algorithm = algorithm;
  }


  public DKIMKeyPairCreateRequest keyLength(@javax.annotation.Nullable Integer keyLength) {
    this.keyLength = keyLength;
    return this;
  }

  /**
   * Key length in bits. For RSA, must be a multiple of 1024. Common values: 1024 or 2048. Defaults to 2048 bits. 
   * minimum: 1024
   * maximum: 4096
   * @return keyLength
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KEY_LENGTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getKeyLength() {
    return keyLength;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY_LENGTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeyLength(@javax.annotation.Nullable Integer keyLength) {
    this.keyLength = keyLength;
  }


  public DKIMKeyPairCreateRequest selector(@javax.annotation.Nonnull String selector) {
    this.selector = selector;
    return this;
  }

  /**
   * Selector for the new key pair 
   * @return selector
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SELECTOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSelector() {
    return selector;
  }


  @JsonProperty(value = JSON_PROPERTY_SELECTOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSelector(@javax.annotation.Nonnull String selector) {
    this.selector = selector;
  }


  /**
   * Return true if this DKIMKeyPairCreateRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DKIMKeyPairCreateRequest dkIMKeyPairCreateRequest = (DKIMKeyPairCreateRequest) o;
    return Objects.equals(this.algorithm, dkIMKeyPairCreateRequest.algorithm) &&
        Objects.equals(this.keyLength, dkIMKeyPairCreateRequest.keyLength) &&
        Objects.equals(this.selector, dkIMKeyPairCreateRequest.selector);
  }

  @Override
  public int hashCode() {
    return Objects.hash(algorithm, keyLength, selector);
  }

  @Override
  public String toString() {
    return "DKIMKeyPairCreateRequest { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `algorithm` to the URL query string
    if (getAlgorithm() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%salgorithm%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAlgorithm()))));
    }

    // add `key_length` to the URL query string
    if (getKeyLength() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skey_length%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKeyLength()))));
    }

    // add `selector` to the URL query string
    if (getSelector() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sselector%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSelector()))));
    }

    return joiner.toString();
  }
}

