/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.mailchannels.model.DKIMKeyInfo;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * DKIMKeyRotateResponse
 */
@JsonPropertyOrder({
  DKIMKeyRotateResponse.JSON_PROPERTY_NEW_KEY,
  DKIMKeyRotateResponse.JSON_PROPERTY_ROTATED_KEY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class DKIMKeyRotateResponse {
  public static final String JSON_PROPERTY_NEW_KEY = "new_key";
  @javax.annotation.Nonnull
  private DKIMKeyInfo newKey;

  public static final String JSON_PROPERTY_ROTATED_KEY = "rotated_key";
  @javax.annotation.Nonnull
  private DKIMKeyInfo rotatedKey;

  public DKIMKeyRotateResponse() { 
  }

  public DKIMKeyRotateResponse newKey(@javax.annotation.Nonnull DKIMKeyInfo newKey) {
    this.newKey = newKey;
    return this;
  }

  /**
   * Get newKey
   * @return newKey
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NEW_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public DKIMKeyInfo getNewKey() {
    return newKey;
  }


  @JsonProperty(value = JSON_PROPERTY_NEW_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNewKey(@javax.annotation.Nonnull DKIMKeyInfo newKey) {
    this.newKey = newKey;
  }


  public DKIMKeyRotateResponse rotatedKey(@javax.annotation.Nonnull DKIMKeyInfo rotatedKey) {
    this.rotatedKey = rotatedKey;
    return this;
  }

  /**
   * Get rotatedKey
   * @return rotatedKey
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ROTATED_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public DKIMKeyInfo getRotatedKey() {
    return rotatedKey;
  }


  @JsonProperty(value = JSON_PROPERTY_ROTATED_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRotatedKey(@javax.annotation.Nonnull DKIMKeyInfo rotatedKey) {
    this.rotatedKey = rotatedKey;
  }


  /**
   * Return true if this DKIMKeyRotateResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DKIMKeyRotateResponse dkIMKeyRotateResponse = (DKIMKeyRotateResponse) o;
    return Objects.equals(this.newKey, dkIMKeyRotateResponse.newKey) &&
        Objects.equals(this.rotatedKey, dkIMKeyRotateResponse.rotatedKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newKey, rotatedKey);
  }

  @Override
  public String toString() {
    return "DKIMKeyRotateResponse { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `new_key` to the URL query string
    if (getNewKey() != null) {
      joiner.add(getNewKey().toUrlQueryString(prefix + "new_key" + suffix));
    }

    // add `rotated_key` to the URL query string
    if (getRotatedKey() != null) {
      joiner.add(getRotatedKey().toUrlQueryString(prefix + "rotated_key" + suffix));
    }

    return joiner.toString();
  }
}

