/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * DnsSetupRequired
 */
@JsonPropertyOrder({
  DnsSetupRequired.JSON_PROPERTY_INSTRUCTIONS,
  DnsSetupRequired.JSON_PROPERTY_TOKEN,
  DnsSetupRequired.JSON_PROPERTY_TXT_RECORD_NAME,
  DnsSetupRequired.JSON_PROPERTY_TXT_RECORD_VALUE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class DnsSetupRequired {
  public static final String JSON_PROPERTY_INSTRUCTIONS = "instructions";
  @javax.annotation.Nullable
  private String instructions;

  public static final String JSON_PROPERTY_TOKEN = "token";
  @javax.annotation.Nullable
  private String token;

  public static final String JSON_PROPERTY_TXT_RECORD_NAME = "txt_record_name";
  @javax.annotation.Nullable
  private String txtRecordName;

  public static final String JSON_PROPERTY_TXT_RECORD_VALUE = "txt_record_value";
  @javax.annotation.Nullable
  private String txtRecordValue;

  public DnsSetupRequired() { 
  }

  public DnsSetupRequired instructions(@javax.annotation.Nullable String instructions) {
    this.instructions = instructions;
    return this;
  }

  /**
   * Human-readable guidance for the DNS records that must be in place before retrying.
   * @return instructions
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INSTRUCTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getInstructions() {
    return instructions;
  }


  @JsonProperty(value = JSON_PROPERTY_INSTRUCTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstructions(@javax.annotation.Nullable String instructions) {
    this.instructions = instructions;
  }


  public DnsSetupRequired token(@javax.annotation.Nullable String token) {
    this.token = token;
    return this;
  }

  /**
   * UUID v4 nonce; also the TXT record value to set. Present only when TXT ownership verification is pending.
   * @return token
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getToken() {
    return token;
  }


  @JsonProperty(value = JSON_PROPERTY_TOKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToken(@javax.annotation.Nullable String token) {
    this.token = token;
  }


  public DnsSetupRequired txtRecordName(@javax.annotation.Nullable String txtRecordName) {
    this.txtRecordName = txtRecordName;
    return this;
  }

  /**
   * Fully-qualified DNS TXT record name to add. Present only when TXT ownership verification is pending.
   * @return txtRecordName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TXT_RECORD_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTxtRecordName() {
    return txtRecordName;
  }


  @JsonProperty(value = JSON_PROPERTY_TXT_RECORD_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTxtRecordName(@javax.annotation.Nullable String txtRecordName) {
    this.txtRecordName = txtRecordName;
  }


  public DnsSetupRequired txtRecordValue(@javax.annotation.Nullable String txtRecordValue) {
    this.txtRecordValue = txtRecordValue;
    return this;
  }

  /**
   * Value for the DNS TXT record (same as token). Present only when TXT ownership verification is pending.
   * @return txtRecordValue
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TXT_RECORD_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTxtRecordValue() {
    return txtRecordValue;
  }


  @JsonProperty(value = JSON_PROPERTY_TXT_RECORD_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTxtRecordValue(@javax.annotation.Nullable String txtRecordValue) {
    this.txtRecordValue = txtRecordValue;
  }


  /**
   * Return true if this DnsSetupRequired object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DnsSetupRequired dnsSetupRequired = (DnsSetupRequired) o;
    return Objects.equals(this.instructions, dnsSetupRequired.instructions) &&
        Objects.equals(this.token, dnsSetupRequired.token) &&
        Objects.equals(this.txtRecordName, dnsSetupRequired.txtRecordName) &&
        Objects.equals(this.txtRecordValue, dnsSetupRequired.txtRecordValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instructions, token, txtRecordName, txtRecordValue);
  }

  @Override
  public String toString() {
    return "DnsSetupRequired { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `instructions` to the URL query string
    if (getInstructions() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sinstructions%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInstructions()))));
    }

    // add `token` to the URL query string
    if (getToken() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stoken%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getToken()))));
    }

    // add `txt_record_name` to the URL query string
    if (getTxtRecordName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stxt_record_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTxtRecordName()))));
    }

    // add `txt_record_value` to the URL query string
    if (getTxtRecordValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stxt_record_value%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTxtRecordValue()))));
    }

    return joiner.toString();
  }
}

