/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * MailSendBodyTrackingSettingsClickTracking
 */
@JsonPropertyOrder({
  MailSendBodyTrackingSettingsClickTracking.JSON_PROPERTY_CUSTOM_DOMAIN_NAME,
  MailSendBodyTrackingSettingsClickTracking.JSON_PROPERTY_ENABLE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class MailSendBodyTrackingSettingsClickTracking {
  public static final String JSON_PROPERTY_CUSTOM_DOMAIN_NAME = "custom_domain_name";
  @javax.annotation.Nullable
  private String customDomainName;

  public static final String JSON_PROPERTY_ENABLE = "enable";
  @javax.annotation.Nullable
  private Boolean enable = false;

  public MailSendBodyTrackingSettingsClickTracking() { 
  }

  public MailSendBodyTrackingSettingsClickTracking customDomainName(@javax.annotation.Nullable String customDomainName) {
    this.customDomainName = customDomainName;
    return this;
  }

  /**
   * The name of a configured active click tracking domain. When specified, click tracking links will use this domain instead of the default MailChannels domain. The domain must be registered in your account and have an active status. 
   * @return customDomainName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_DOMAIN_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCustomDomainName() {
    return customDomainName;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_DOMAIN_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomDomainName(@javax.annotation.Nullable String customDomainName) {
    this.customDomainName = customDomainName;
  }


  public MailSendBodyTrackingSettingsClickTracking enable(@javax.annotation.Nullable Boolean enable) {
    this.enable = enable;
    return this;
  }

  /**
   * Setting to enable or disable click tracking for the message. This feature allows you to track when a recipient clicks a link in your email. 
   * @return enable
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getEnable() {
    return enable;
  }


  @JsonProperty(value = JSON_PROPERTY_ENABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnable(@javax.annotation.Nullable Boolean enable) {
    this.enable = enable;
  }


  /**
   * Return true if this MailSendBody_tracking_settings_click_tracking object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailSendBodyTrackingSettingsClickTracking mailSendBodyTrackingSettingsClickTracking = (MailSendBodyTrackingSettingsClickTracking) o;
    return Objects.equals(this.customDomainName, mailSendBodyTrackingSettingsClickTracking.customDomainName) &&
        Objects.equals(this.enable, mailSendBodyTrackingSettingsClickTracking.enable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customDomainName, enable);
  }

  @Override
  public String toString() {
    return "MailSendBodyTrackingSettingsClickTracking { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `custom_domain_name` to the URL query string
    if (getCustomDomainName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scustom_domain_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCustomDomainName()))));
    }

    // add `enable` to the URL query string
    if (getEnable() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%senable%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEnable()))));
    }

    return joiner.toString();
  }
}

