/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.mailchannels.model.Attachment;
import com.mailchannels.model.ContentItem;
import com.mailchannels.model.EmailAddress;
import com.mailchannels.model.MailSendBodyTrackingSettings;
import com.mailchannels.model.MailSendBodyUnsubscribeSettings;
import com.mailchannels.model.Personalization;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * MailSendBody
 */
@JsonPropertyOrder({
  MailSendBody.JSON_PROPERTY_ATTACHMENTS,
  MailSendBody.JSON_PROPERTY_CAMPAIGN_ID,
  MailSendBody.JSON_PROPERTY_CONTENT,
  MailSendBody.JSON_PROPERTY_DKIM_DOMAIN,
  MailSendBody.JSON_PROPERTY_DKIM_PRIVATE_KEY,
  MailSendBody.JSON_PROPERTY_DKIM_SELECTOR,
  MailSendBody.JSON_PROPERTY_ENVELOPE_FROM,
  MailSendBody.JSON_PROPERTY_FROM,
  MailSendBody.JSON_PROPERTY_HEADERS,
  MailSendBody.JSON_PROPERTY_PERSONALIZATIONS,
  MailSendBody.JSON_PROPERTY_REPLY_TO,
  MailSendBody.JSON_PROPERTY_SUBJECT,
  MailSendBody.JSON_PROPERTY_TRACKING_SETTINGS,
  MailSendBody.JSON_PROPERTY_TRANSACTIONAL,
  MailSendBody.JSON_PROPERTY_UNSUBSCRIBE_SETTINGS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class MailSendBody {
  public static final String JSON_PROPERTY_ATTACHMENTS = "attachments";
  @javax.annotation.Nullable
  private List<Attachment> attachments = new ArrayList<>();

  public static final String JSON_PROPERTY_CAMPAIGN_ID = "campaign_id";
  @javax.annotation.Nullable
  private String campaignId;

  public static final String JSON_PROPERTY_CONTENT = "content";
  @javax.annotation.Nonnull
  private List<ContentItem> content = new ArrayList<>();

  public static final String JSON_PROPERTY_DKIM_DOMAIN = "dkim_domain";
  @javax.annotation.Nullable
  private String dkimDomain;

  public static final String JSON_PROPERTY_DKIM_PRIVATE_KEY = "dkim_private_key";
  @javax.annotation.Nullable
  private String dkimPrivateKey;

  public static final String JSON_PROPERTY_DKIM_SELECTOR = "dkim_selector";
  @javax.annotation.Nullable
  private String dkimSelector;

  public static final String JSON_PROPERTY_ENVELOPE_FROM = "envelope_from";
  @javax.annotation.Nullable
  private EmailAddress envelopeFrom;

  public static final String JSON_PROPERTY_FROM = "from";
  @javax.annotation.Nonnull
  private EmailAddress from;

  public static final String JSON_PROPERTY_HEADERS = "headers";
  @javax.annotation.Nullable
  private Map<String, String> headers = new HashMap<>();

  public static final String JSON_PROPERTY_PERSONALIZATIONS = "personalizations";
  @javax.annotation.Nonnull
  private List<Personalization> personalizations = new ArrayList<>();

  public static final String JSON_PROPERTY_REPLY_TO = "reply_to";
  @javax.annotation.Nullable
  private EmailAddress replyTo;

  public static final String JSON_PROPERTY_SUBJECT = "subject";
  @javax.annotation.Nonnull
  private String subject;

  public static final String JSON_PROPERTY_TRACKING_SETTINGS = "tracking_settings";
  @javax.annotation.Nullable
  private MailSendBodyTrackingSettings trackingSettings;

  public static final String JSON_PROPERTY_TRANSACTIONAL = "transactional";
  private JsonNullable<Boolean> transactional = JsonNullable.<Boolean>of(true);

  public static final String JSON_PROPERTY_UNSUBSCRIBE_SETTINGS = "unsubscribe_settings";
  @javax.annotation.Nullable
  private MailSendBodyUnsubscribeSettings unsubscribeSettings;

  public MailSendBody() { 
  }

  public MailSendBody attachments(@javax.annotation.Nullable List<Attachment> attachments) {
    this.attachments = attachments;
    return this;
  }

  public MailSendBody addAttachmentsItem(Attachment attachmentsItem) {
    if (this.attachments == null) {
      this.attachments = new ArrayList<>();
    }
    this.attachments.add(attachmentsItem);
    return this;
  }

  /**
   * Get attachments
   * @return attachments
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ATTACHMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Attachment> getAttachments() {
    return attachments;
  }


  @JsonProperty(value = JSON_PROPERTY_ATTACHMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAttachments(@javax.annotation.Nullable List<Attachment> attachments) {
    this.attachments = attachments;
  }


  public MailSendBody campaignId(@javax.annotation.Nullable String campaignId) {
    this.campaignId = campaignId;
    return this;
  }

  /**
   * The campaign identifier. If specified, this ID will be included in all relevant webhooks. It can be up to 48 UTF-8 characters long and must not contain spaces. 
   * @return campaignId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CAMPAIGN_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCampaignId() {
    return campaignId;
  }


  @JsonProperty(value = JSON_PROPERTY_CAMPAIGN_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCampaignId(@javax.annotation.Nullable String campaignId) {
    this.campaignId = campaignId;
  }


  public MailSendBody content(@javax.annotation.Nonnull List<ContentItem> content) {
    this.content = content;
    return this;
  }

  public MailSendBody addContentItem(ContentItem contentItem) {
    if (this.content == null) {
      this.content = new ArrayList<>();
    }
    this.content.add(contentItem);
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<ContentItem> getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContent(@javax.annotation.Nonnull List<ContentItem> content) {
    this.content = content;
  }


  public MailSendBody dkimDomain(@javax.annotation.Nullable String dkimDomain) {
    this.dkimDomain = dkimDomain;
    return this;
  }

  /**
   * If set, you must also provide the matching dkim_selector. 
   * @return dkimDomain
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DKIM_DOMAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDkimDomain() {
    return dkimDomain;
  }


  @JsonProperty(value = JSON_PROPERTY_DKIM_DOMAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDkimDomain(@javax.annotation.Nullable String dkimDomain) {
    this.dkimDomain = dkimDomain;
  }


  public MailSendBody dkimPrivateKey(@javax.annotation.Nullable String dkimPrivateKey) {
    this.dkimPrivateKey = dkimPrivateKey;
    return this;
  }

  /**
   * Encoded in Base64. If set, you must also provide the matching dkim_domain and dkim_selector. 
   * @return dkimPrivateKey
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DKIM_PRIVATE_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDkimPrivateKey() {
    return dkimPrivateKey;
  }


  @JsonProperty(value = JSON_PROPERTY_DKIM_PRIVATE_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDkimPrivateKey(@javax.annotation.Nullable String dkimPrivateKey) {
    this.dkimPrivateKey = dkimPrivateKey;
  }


  public MailSendBody dkimSelector(@javax.annotation.Nullable String dkimSelector) {
    this.dkimSelector = dkimSelector;
    return this;
  }

  /**
   * If set without a matching dkim_domain, the domain will be taken from the &#x60;from&#x60; email address. 
   * @return dkimSelector
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DKIM_SELECTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDkimSelector() {
    return dkimSelector;
  }


  @JsonProperty(value = JSON_PROPERTY_DKIM_SELECTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDkimSelector(@javax.annotation.Nullable String dkimSelector) {
    this.dkimSelector = dkimSelector;
  }


  public MailSendBody envelopeFrom(@javax.annotation.Nullable EmailAddress envelopeFrom) {
    this.envelopeFrom = envelopeFrom;
    return this;
  }

  /**
   * Get envelopeFrom
   * @return envelopeFrom
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENVELOPE_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EmailAddress getEnvelopeFrom() {
    return envelopeFrom;
  }


  @JsonProperty(value = JSON_PROPERTY_ENVELOPE_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnvelopeFrom(@javax.annotation.Nullable EmailAddress envelopeFrom) {
    this.envelopeFrom = envelopeFrom;
  }


  public MailSendBody from(@javax.annotation.Nonnull EmailAddress from) {
    this.from = from;
    return this;
  }

  /**
   * Get from
   * @return from
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public EmailAddress getFrom() {
    return from;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFrom(@javax.annotation.Nonnull EmailAddress from) {
    this.from = from;
  }


  public MailSendBody headers(@javax.annotation.Nullable Map<String, String> headers) {
    this.headers = headers;
    return this;
  }

  public MailSendBody putHeadersItem(String key, String headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

  /**
   * A JSON object containing key-value pairs, where both keys (header names) and values must be strings. These pairs represent custom headers to be substituted. Please note the following restrictions and behavior: - Reserved headers: The following headers cannot be modified:   - Authentication-Results   - BCC   - CC   - Content-Transfer-Encoding   - Content-Type   - DKIM-Signature   - From   - Message-ID   - Received   - Reply-To   - Subject   - To - Header precedence: If a header is defined in both the personalizations object and the root headers, the value from personalizations will be used. - Case sensitivity: Headers are treated as case-insensitive. If multiple headers differ only by case, only one will be used, with no guarantee of which one. 
   * @return headers
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, String> getHeaders() {
    return headers;
  }


  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeaders(@javax.annotation.Nullable Map<String, String> headers) {
    this.headers = headers;
  }


  public MailSendBody personalizations(@javax.annotation.Nonnull List<Personalization> personalizations) {
    this.personalizations = personalizations;
    return this;
  }

  public MailSendBody addPersonalizationsItem(Personalization personalizationsItem) {
    if (this.personalizations == null) {
      this.personalizations = new ArrayList<>();
    }
    this.personalizations.add(personalizationsItem);
    return this;
  }

  /**
   * Get personalizations
   * @return personalizations
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PERSONALIZATIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<Personalization> getPersonalizations() {
    return personalizations;
  }


  @JsonProperty(value = JSON_PROPERTY_PERSONALIZATIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPersonalizations(@javax.annotation.Nonnull List<Personalization> personalizations) {
    this.personalizations = personalizations;
  }


  public MailSendBody replyTo(@javax.annotation.Nullable EmailAddress replyTo) {
    this.replyTo = replyTo;
    return this;
  }

  /**
   * Get replyTo
   * @return replyTo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REPLY_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EmailAddress getReplyTo() {
    return replyTo;
  }


  @JsonProperty(value = JSON_PROPERTY_REPLY_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplyTo(@javax.annotation.Nullable EmailAddress replyTo) {
    this.replyTo = replyTo;
  }


  public MailSendBody subject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * Get subject
   * @return subject
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSubject() {
    return subject;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
  }


  public MailSendBody trackingSettings(@javax.annotation.Nullable MailSendBodyTrackingSettings trackingSettings) {
    this.trackingSettings = trackingSettings;
    return this;
  }

  /**
   * Get trackingSettings
   * @return trackingSettings
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRACKING_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public MailSendBodyTrackingSettings getTrackingSettings() {
    return trackingSettings;
  }


  @JsonProperty(value = JSON_PROPERTY_TRACKING_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackingSettings(@javax.annotation.Nullable MailSendBodyTrackingSettings trackingSettings) {
    this.trackingSettings = trackingSettings;
  }


  public MailSendBody transactional(@javax.annotation.Nullable Boolean transactional) {
    this.transactional = JsonNullable.<Boolean>of(transactional);
    return this;
  }

  /**
   * Mark these messages as transactional or non-transactional. In order for a message to be marked as non-transactional, it must have exactly one recipient per personalization, and it must be DKIM signed. 400 Bad Request will be returned if there are more than one recipient in any personalization for non-transactional messages. If a message is marked as non-transactional, it changes the sending process as follows:   * List-Unsubscribe and List-Unsubscribe-Post headers will be added, unless you supply your own List-Unsubscribe header, in which case yours is used and neither is added. 
   * @return transactional
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Boolean getTransactional() {
        return transactional.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TRANSACTIONAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getTransactional_JsonNullable() {
    return transactional;
  }
  
  @JsonProperty(JSON_PROPERTY_TRANSACTIONAL)
  public void setTransactional_JsonNullable(JsonNullable<Boolean> transactional) {
    this.transactional = transactional;
  }

  public void setTransactional(@javax.annotation.Nullable Boolean transactional) {
    this.transactional = JsonNullable.<Boolean>of(transactional);
  }


  public MailSendBody unsubscribeSettings(@javax.annotation.Nullable MailSendBodyUnsubscribeSettings unsubscribeSettings) {
    this.unsubscribeSettings = unsubscribeSettings;
    return this;
  }

  /**
   * Get unsubscribeSettings
   * @return unsubscribeSettings
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UNSUBSCRIBE_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public MailSendBodyUnsubscribeSettings getUnsubscribeSettings() {
    return unsubscribeSettings;
  }


  @JsonProperty(value = JSON_PROPERTY_UNSUBSCRIBE_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnsubscribeSettings(@javax.annotation.Nullable MailSendBodyUnsubscribeSettings unsubscribeSettings) {
    this.unsubscribeSettings = unsubscribeSettings;
  }


  /**
   * Return true if this MailSendBody object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailSendBody mailSendBody = (MailSendBody) o;
    return Objects.equals(this.attachments, mailSendBody.attachments) &&
        Objects.equals(this.campaignId, mailSendBody.campaignId) &&
        Objects.equals(this.content, mailSendBody.content) &&
        Objects.equals(this.dkimDomain, mailSendBody.dkimDomain) &&
        Objects.equals(this.dkimPrivateKey, mailSendBody.dkimPrivateKey) &&
        Objects.equals(this.dkimSelector, mailSendBody.dkimSelector) &&
        Objects.equals(this.envelopeFrom, mailSendBody.envelopeFrom) &&
        Objects.equals(this.from, mailSendBody.from) &&
        Objects.equals(this.headers, mailSendBody.headers) &&
        Objects.equals(this.personalizations, mailSendBody.personalizations) &&
        Objects.equals(this.replyTo, mailSendBody.replyTo) &&
        Objects.equals(this.subject, mailSendBody.subject) &&
        Objects.equals(this.trackingSettings, mailSendBody.trackingSettings) &&
        equalsNullable(this.transactional, mailSendBody.transactional) &&
        Objects.equals(this.unsubscribeSettings, mailSendBody.unsubscribeSettings);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(attachments, campaignId, content, dkimDomain, dkimPrivateKey, dkimSelector, envelopeFrom, from, headers, personalizations, replyTo, subject, trackingSettings, hashCodeNullable(transactional), unsubscribeSettings);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    return "MailSendBody { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `attachments` to the URL query string
    if (getAttachments() != null) {
      for (int i = 0; i < getAttachments().size(); i++) {
        if (getAttachments().get(i) != null) {
          joiner.add(getAttachments().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sattachments%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `campaign_id` to the URL query string
    if (getCampaignId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scampaign_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCampaignId()))));
    }

    // add `content` to the URL query string
    if (getContent() != null) {
      for (int i = 0; i < getContent().size(); i++) {
        if (getContent().get(i) != null) {
          joiner.add(getContent().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%scontent%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `dkim_domain` to the URL query string
    if (getDkimDomain() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdkim_domain%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDkimDomain()))));
    }

    // add `dkim_private_key` to the URL query string
    if (getDkimPrivateKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdkim_private_key%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDkimPrivateKey()))));
    }

    // add `dkim_selector` to the URL query string
    if (getDkimSelector() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdkim_selector%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDkimSelector()))));
    }

    // add `envelope_from` to the URL query string
    if (getEnvelopeFrom() != null) {
      joiner.add(getEnvelopeFrom().toUrlQueryString(prefix + "envelope_from" + suffix));
    }

    // add `from` to the URL query string
    if (getFrom() != null) {
      joiner.add(getFrom().toUrlQueryString(prefix + "from" + suffix));
    }

    // add `headers` to the URL query string
    if (getHeaders() != null) {
      for (String _key : getHeaders().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sheaders%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getHeaders().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getHeaders().get(_key)))));
      }
    }

    // add `personalizations` to the URL query string
    if (getPersonalizations() != null) {
      for (int i = 0; i < getPersonalizations().size(); i++) {
        if (getPersonalizations().get(i) != null) {
          joiner.add(getPersonalizations().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%spersonalizations%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `reply_to` to the URL query string
    if (getReplyTo() != null) {
      joiner.add(getReplyTo().toUrlQueryString(prefix + "reply_to" + suffix));
    }

    // add `subject` to the URL query string
    if (getSubject() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubject()))));
    }

    // add `tracking_settings` to the URL query string
    if (getTrackingSettings() != null) {
      joiner.add(getTrackingSettings().toUrlQueryString(prefix + "tracking_settings" + suffix));
    }

    // add `transactional` to the URL query string
    if (getTransactional() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stransactional%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTransactional()))));
    }

    // add `unsubscribe_settings` to the URL query string
    if (getUnsubscribeSettings() != null) {
      joiner.add(getUnsubscribeSettings().toUrlQueryString(prefix + "unsubscribe_settings" + suffix));
    }

    return joiner.toString();
  }
}

