/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * Represents a time-based bucket for aggregating metrics data. Each bucket corresponds to a specific time interval, with the &#x60;period_start&#x60; indicating the beginning of that interval. The &#x60;count&#x60; field represents the number of events or occurrences that fall within that time period. 
 */
@JsonPropertyOrder({
  MetricsBucket.JSON_PROPERTY_COUNT,
  MetricsBucket.JSON_PROPERTY_PERIOD_START
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class MetricsBucket {
  public static final String JSON_PROPERTY_COUNT = "count";
  @javax.annotation.Nonnull
  private Integer count;

  public static final String JSON_PROPERTY_PERIOD_START = "period_start";
  @javax.annotation.Nonnull
  private OffsetDateTime periodStart;

  public MetricsBucket() { 
  }

  public MetricsBucket count(@javax.annotation.Nonnull Integer count) {
    this.count = count;
    return this;
  }

  /**
   * The number of events or occurrences aggregated within this time period.
   * minimum: 0
   * @return count
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getCount() {
    return count;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCount(@javax.annotation.Nonnull Integer count) {
    this.count = count;
  }


  public MetricsBucket periodStart(@javax.annotation.Nonnull OffsetDateTime periodStart) {
    this.periodStart = periodStart;
    return this;
  }

  /**
   * The starting date and time of the time period this bucket represents.
   * @return periodStart
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PERIOD_START, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getPeriodStart() {
    return periodStart;
  }


  @JsonProperty(value = JSON_PROPERTY_PERIOD_START, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPeriodStart(@javax.annotation.Nonnull OffsetDateTime periodStart) {
    this.periodStart = periodStart;
  }


  /**
   * Return true if this MetricsBucket object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetricsBucket metricsBucket = (MetricsBucket) o;
    return Objects.equals(this.count, metricsBucket.count) &&
        Objects.equals(this.periodStart, metricsBucket.periodStart);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, periodStart);
  }

  @Override
  public String toString() {
    return "MetricsBucket { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `count` to the URL query string
    if (getCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCount()))));
    }

    // add `period_start` to the URL query string
    if (getPeriodStart() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%speriod_start%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPeriodStart()))));
    }

    return joiner.toString();
  }
}

