/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.mailchannels.model.MetricsSender;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * MetricsSenderResponse
 */
@JsonPropertyOrder({
  MetricsSenderResponse.JSON_PROPERTY_END_TIME,
  MetricsSenderResponse.JSON_PROPERTY_LIMIT,
  MetricsSenderResponse.JSON_PROPERTY_OFFSET,
  MetricsSenderResponse.JSON_PROPERTY_SENDERS,
  MetricsSenderResponse.JSON_PROPERTY_START_TIME,
  MetricsSenderResponse.JSON_PROPERTY_TOTAL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class MetricsSenderResponse {
  public static final String JSON_PROPERTY_END_TIME = "end_time";
  @javax.annotation.Nullable
  private OffsetDateTime endTime;

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @javax.annotation.Nonnull
  private Integer limit;

  public static final String JSON_PROPERTY_OFFSET = "offset";
  @javax.annotation.Nonnull
  private Integer offset;

  public static final String JSON_PROPERTY_SENDERS = "senders";
  @javax.annotation.Nonnull
  private List<MetricsSender> senders = new ArrayList<>();

  public static final String JSON_PROPERTY_START_TIME = "start_time";
  @javax.annotation.Nullable
  private OffsetDateTime startTime;

  public static final String JSON_PROPERTY_TOTAL = "total";
  @javax.annotation.Nonnull
  private Integer total;

  public MetricsSenderResponse() { 
  }

  public MetricsSenderResponse endTime(@javax.annotation.Nullable OffsetDateTime endTime) {
    this.endTime = endTime;
    return this;
  }

  /**
   * Get endTime
   * @return endTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_END_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getEndTime() {
    return endTime;
  }


  @JsonProperty(value = JSON_PROPERTY_END_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndTime(@javax.annotation.Nullable OffsetDateTime endTime) {
    this.endTime = endTime;
  }


  public MetricsSenderResponse limit(@javax.annotation.Nonnull Integer limit) {
    this.limit = limit;
    return this;
  }

  /**
   * Get limit
   * @return limit
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getLimit() {
    return limit;
  }


  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLimit(@javax.annotation.Nonnull Integer limit) {
    this.limit = limit;
  }


  public MetricsSenderResponse offset(@javax.annotation.Nonnull Integer offset) {
    this.offset = offset;
    return this;
  }

  /**
   * Get offset
   * @return offset
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OFFSET, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getOffset() {
    return offset;
  }


  @JsonProperty(value = JSON_PROPERTY_OFFSET, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOffset(@javax.annotation.Nonnull Integer offset) {
    this.offset = offset;
  }


  public MetricsSenderResponse senders(@javax.annotation.Nonnull List<MetricsSender> senders) {
    this.senders = senders;
    return this;
  }

  public MetricsSenderResponse addSendersItem(MetricsSender sendersItem) {
    if (this.senders == null) {
      this.senders = new ArrayList<>();
    }
    this.senders.add(sendersItem);
    return this;
  }

  /**
   * Get senders
   * @return senders
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SENDERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<MetricsSender> getSenders() {
    return senders;
  }


  @JsonProperty(value = JSON_PROPERTY_SENDERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSenders(@javax.annotation.Nonnull List<MetricsSender> senders) {
    this.senders = senders;
  }


  public MetricsSenderResponse startTime(@javax.annotation.Nullable OffsetDateTime startTime) {
    this.startTime = startTime;
    return this;
  }

  /**
   * Get startTime
   * @return startTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getStartTime() {
    return startTime;
  }


  @JsonProperty(value = JSON_PROPERTY_START_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(@javax.annotation.Nullable OffsetDateTime startTime) {
    this.startTime = startTime;
  }


  public MetricsSenderResponse total(@javax.annotation.Nonnull Integer total) {
    this.total = total;
    return this;
  }

  /**
   * The total number of senders in this category that sent messages in the given time range. 
   * @return total
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getTotal() {
    return total;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotal(@javax.annotation.Nonnull Integer total) {
    this.total = total;
  }


  /**
   * Return true if this MetricsSenderResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetricsSenderResponse metricsSenderResponse = (MetricsSenderResponse) o;
    return Objects.equals(this.endTime, metricsSenderResponse.endTime) &&
        Objects.equals(this.limit, metricsSenderResponse.limit) &&
        Objects.equals(this.offset, metricsSenderResponse.offset) &&
        Objects.equals(this.senders, metricsSenderResponse.senders) &&
        Objects.equals(this.startTime, metricsSenderResponse.startTime) &&
        Objects.equals(this.total, metricsSenderResponse.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endTime, limit, offset, senders, startTime, total);
  }

  @Override
  public String toString() {
    return "MetricsSenderResponse { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `end_time` to the URL query string
    if (getEndTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%send_time%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndTime()))));
    }

    // add `limit` to the URL query string
    if (getLimit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slimit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLimit()))));
    }

    // add `offset` to the URL query string
    if (getOffset() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soffset%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOffset()))));
    }

    // add `senders` to the URL query string
    if (getSenders() != null) {
      for (int i = 0; i < getSenders().size(); i++) {
        if (getSenders().get(i) != null) {
          joiner.add(getSenders().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%ssenders%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `start_time` to the URL query string
    if (getStartTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstart_time%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStartTime()))));
    }

    // add `total` to the URL query string
    if (getTotal() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotal%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotal()))));
    }

    return joiner.toString();
  }
}

