/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.mailchannels.model.MetricsRecipientBehaviourBuckets;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * MetricsRecipientBehaviour
 */
@JsonPropertyOrder({
  MetricsRecipientBehaviour.JSON_PROPERTY_BUCKETS,
  MetricsRecipientBehaviour.JSON_PROPERTY_END_TIME,
  MetricsRecipientBehaviour.JSON_PROPERTY_START_TIME,
  MetricsRecipientBehaviour.JSON_PROPERTY_UNSUBSCRIBE_DELIVERED,
  MetricsRecipientBehaviour.JSON_PROPERTY_UNSUBSCRIBED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class MetricsRecipientBehaviour {
  public static final String JSON_PROPERTY_BUCKETS = "buckets";
  @javax.annotation.Nonnull
  private MetricsRecipientBehaviourBuckets buckets;

  public static final String JSON_PROPERTY_END_TIME = "end_time";
  @javax.annotation.Nullable
  private OffsetDateTime endTime;

  public static final String JSON_PROPERTY_START_TIME = "start_time";
  @javax.annotation.Nullable
  private OffsetDateTime startTime;

  public static final String JSON_PROPERTY_UNSUBSCRIBE_DELIVERED = "unsubscribe_delivered";
  @javax.annotation.Nonnull
  private Integer unsubscribeDelivered;

  public static final String JSON_PROPERTY_UNSUBSCRIBED = "unsubscribed";
  @javax.annotation.Nonnull
  private Integer unsubscribed;

  public MetricsRecipientBehaviour() { 
  }

  public MetricsRecipientBehaviour buckets(@javax.annotation.Nonnull MetricsRecipientBehaviourBuckets buckets) {
    this.buckets = buckets;
    return this;
  }

  /**
   * Get buckets
   * @return buckets
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BUCKETS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public MetricsRecipientBehaviourBuckets getBuckets() {
    return buckets;
  }


  @JsonProperty(value = JSON_PROPERTY_BUCKETS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBuckets(@javax.annotation.Nonnull MetricsRecipientBehaviourBuckets buckets) {
    this.buckets = buckets;
  }


  public MetricsRecipientBehaviour endTime(@javax.annotation.Nullable OffsetDateTime endTime) {
    this.endTime = endTime;
    return this;
  }

  /**
   * The end of the time range for retrieving recipient behaviour metrics (exclusive). 
   * @return endTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_END_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getEndTime() {
    return endTime;
  }


  @JsonProperty(value = JSON_PROPERTY_END_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndTime(@javax.annotation.Nullable OffsetDateTime endTime) {
    this.endTime = endTime;
  }


  public MetricsRecipientBehaviour startTime(@javax.annotation.Nullable OffsetDateTime startTime) {
    this.startTime = startTime;
    return this;
  }

  /**
   * The beginning of the time range for retrieving recipient behaviour metrics (inclusive). 
   * @return startTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getStartTime() {
    return startTime;
  }


  @JsonProperty(value = JSON_PROPERTY_START_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(@javax.annotation.Nullable OffsetDateTime startTime) {
    this.startTime = startTime;
  }


  public MetricsRecipientBehaviour unsubscribeDelivered(@javax.annotation.Nonnull Integer unsubscribeDelivered) {
    this.unsubscribeDelivered = unsubscribeDelivered;
    return this;
  }

  /**
   * Count of recipients of delivered messages that include at least one of the unsubscribe link or unsubscribe headers. Since the unsubscribe feature requires exactly one recipient per message, this count also represents the total number of delivered messages. 
   * minimum: 0
   * @return unsubscribeDelivered
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UNSUBSCRIBE_DELIVERED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getUnsubscribeDelivered() {
    return unsubscribeDelivered;
  }


  @JsonProperty(value = JSON_PROPERTY_UNSUBSCRIBE_DELIVERED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUnsubscribeDelivered(@javax.annotation.Nonnull Integer unsubscribeDelivered) {
    this.unsubscribeDelivered = unsubscribeDelivered;
  }


  public MetricsRecipientBehaviour unsubscribed(@javax.annotation.Nonnull Integer unsubscribed) {
    this.unsubscribed = unsubscribed;
    return this;
  }

  /**
   * Count of unsubscribed events by recipients. 
   * minimum: 0
   * @return unsubscribed
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UNSUBSCRIBED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getUnsubscribed() {
    return unsubscribed;
  }


  @JsonProperty(value = JSON_PROPERTY_UNSUBSCRIBED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUnsubscribed(@javax.annotation.Nonnull Integer unsubscribed) {
    this.unsubscribed = unsubscribed;
  }


  /**
   * Return true if this MetricsRecipientBehaviour object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetricsRecipientBehaviour metricsRecipientBehaviour = (MetricsRecipientBehaviour) o;
    return Objects.equals(this.buckets, metricsRecipientBehaviour.buckets) &&
        Objects.equals(this.endTime, metricsRecipientBehaviour.endTime) &&
        Objects.equals(this.startTime, metricsRecipientBehaviour.startTime) &&
        Objects.equals(this.unsubscribeDelivered, metricsRecipientBehaviour.unsubscribeDelivered) &&
        Objects.equals(this.unsubscribed, metricsRecipientBehaviour.unsubscribed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buckets, endTime, startTime, unsubscribeDelivered, unsubscribed);
  }

  @Override
  public String toString() {
    return "MetricsRecipientBehaviour { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `buckets` to the URL query string
    if (getBuckets() != null) {
      joiner.add(getBuckets().toUrlQueryString(prefix + "buckets" + suffix));
    }

    // add `end_time` to the URL query string
    if (getEndTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%send_time%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndTime()))));
    }

    // add `start_time` to the URL query string
    if (getStartTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstart_time%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStartTime()))));
    }

    // add `unsubscribe_delivered` to the URL query string
    if (getUnsubscribeDelivered() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sunsubscribe_delivered%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUnsubscribeDelivered()))));
    }

    // add `unsubscribed` to the URL query string
    if (getUnsubscribed() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sunsubscribed%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUnsubscribed()))));
    }

    return joiner.toString();
  }
}

