/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.mailchannels.model.MetricsBucket;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * A series of metrics aggregations bucketed by time interval (e.g. hour, day)
 */
@JsonPropertyOrder({
  MetricsVolumeBuckets.JSON_PROPERTY_DELIVERED,
  MetricsVolumeBuckets.JSON_PROPERTY_DROPPED,
  MetricsVolumeBuckets.JSON_PROPERTY_PROCESSED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class MetricsVolumeBuckets {
  public static final String JSON_PROPERTY_DELIVERED = "delivered";
  @javax.annotation.Nonnull
  private List<MetricsBucket> delivered = new ArrayList<>();

  public static final String JSON_PROPERTY_DROPPED = "dropped";
  @javax.annotation.Nonnull
  private List<MetricsBucket> dropped = new ArrayList<>();

  public static final String JSON_PROPERTY_PROCESSED = "processed";
  @javax.annotation.Nonnull
  private List<MetricsBucket> processed = new ArrayList<>();

  public MetricsVolumeBuckets() { 
  }

  public MetricsVolumeBuckets delivered(@javax.annotation.Nonnull List<MetricsBucket> delivered) {
    this.delivered = delivered;
    return this;
  }

  public MetricsVolumeBuckets addDeliveredItem(MetricsBucket deliveredItem) {
    if (this.delivered == null) {
      this.delivered = new ArrayList<>();
    }
    this.delivered.add(deliveredItem);
    return this;
  }

  /**
   * Get delivered
   * @return delivered
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DELIVERED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<MetricsBucket> getDelivered() {
    return delivered;
  }


  @JsonProperty(value = JSON_PROPERTY_DELIVERED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDelivered(@javax.annotation.Nonnull List<MetricsBucket> delivered) {
    this.delivered = delivered;
  }


  public MetricsVolumeBuckets dropped(@javax.annotation.Nonnull List<MetricsBucket> dropped) {
    this.dropped = dropped;
    return this;
  }

  public MetricsVolumeBuckets addDroppedItem(MetricsBucket droppedItem) {
    if (this.dropped == null) {
      this.dropped = new ArrayList<>();
    }
    this.dropped.add(droppedItem);
    return this;
  }

  /**
   * Get dropped
   * @return dropped
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DROPPED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<MetricsBucket> getDropped() {
    return dropped;
  }


  @JsonProperty(value = JSON_PROPERTY_DROPPED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDropped(@javax.annotation.Nonnull List<MetricsBucket> dropped) {
    this.dropped = dropped;
  }


  public MetricsVolumeBuckets processed(@javax.annotation.Nonnull List<MetricsBucket> processed) {
    this.processed = processed;
    return this;
  }

  public MetricsVolumeBuckets addProcessedItem(MetricsBucket processedItem) {
    if (this.processed == null) {
      this.processed = new ArrayList<>();
    }
    this.processed.add(processedItem);
    return this;
  }

  /**
   * Get processed
   * @return processed
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROCESSED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<MetricsBucket> getProcessed() {
    return processed;
  }


  @JsonProperty(value = JSON_PROPERTY_PROCESSED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProcessed(@javax.annotation.Nonnull List<MetricsBucket> processed) {
    this.processed = processed;
  }


  /**
   * Return true if this MetricsVolume_buckets object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetricsVolumeBuckets metricsVolumeBuckets = (MetricsVolumeBuckets) o;
    return Objects.equals(this.delivered, metricsVolumeBuckets.delivered) &&
        Objects.equals(this.dropped, metricsVolumeBuckets.dropped) &&
        Objects.equals(this.processed, metricsVolumeBuckets.processed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(delivered, dropped, processed);
  }

  @Override
  public String toString() {
    return "MetricsVolumeBuckets { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `delivered` to the URL query string
    if (getDelivered() != null) {
      for (int i = 0; i < getDelivered().size(); i++) {
        if (getDelivered().get(i) != null) {
          joiner.add(getDelivered().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdelivered%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `dropped` to the URL query string
    if (getDropped() != null) {
      for (int i = 0; i < getDropped().size(); i++) {
        if (getDropped().get(i) != null) {
          joiner.add(getDropped().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdropped%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `processed` to the URL query string
    if (getProcessed() != null) {
      for (int i = 0; i < getProcessed().size(); i++) {
        if (getProcessed().get(i) != null) {
          joiner.add(getProcessed().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sprocessed%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

