/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.mailchannels.model.MetricsPerformanceBuckets;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * MetricsPerformance
 */
@JsonPropertyOrder({
  MetricsPerformance.JSON_PROPERTY_BOUNCED,
  MetricsPerformance.JSON_PROPERTY_BUCKETS,
  MetricsPerformance.JSON_PROPERTY_COMPLAINED,
  MetricsPerformance.JSON_PROPERTY_DELIVERED,
  MetricsPerformance.JSON_PROPERTY_END_TIME,
  MetricsPerformance.JSON_PROPERTY_PROCESSED,
  MetricsPerformance.JSON_PROPERTY_START_TIME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class MetricsPerformance {
  public static final String JSON_PROPERTY_BOUNCED = "bounced";
  @javax.annotation.Nonnull
  private Integer bounced;

  public static final String JSON_PROPERTY_BUCKETS = "buckets";
  @javax.annotation.Nonnull
  private MetricsPerformanceBuckets buckets;

  public static final String JSON_PROPERTY_COMPLAINED = "complained";
  @javax.annotation.Nonnull
  private Integer complained;

  public static final String JSON_PROPERTY_DELIVERED = "delivered";
  @javax.annotation.Nonnull
  private Integer delivered;

  public static final String JSON_PROPERTY_END_TIME = "end_time";
  @javax.annotation.Nullable
  private OffsetDateTime endTime;

  public static final String JSON_PROPERTY_PROCESSED = "processed";
  @javax.annotation.Nonnull
  private Integer processed;

  public static final String JSON_PROPERTY_START_TIME = "start_time";
  @javax.annotation.Nullable
  private OffsetDateTime startTime;

  public MetricsPerformance() { 
  }

  public MetricsPerformance bounced(@javax.annotation.Nonnull Integer bounced) {
    this.bounced = bounced;
    return this;
  }

  /**
   * Count of messages hard-bounced during the specified time range. 
   * minimum: 0
   * @return bounced
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BOUNCED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getBounced() {
    return bounced;
  }


  @JsonProperty(value = JSON_PROPERTY_BOUNCED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBounced(@javax.annotation.Nonnull Integer bounced) {
    this.bounced = bounced;
  }


  public MetricsPerformance buckets(@javax.annotation.Nonnull MetricsPerformanceBuckets buckets) {
    this.buckets = buckets;
    return this;
  }

  /**
   * Get buckets
   * @return buckets
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BUCKETS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public MetricsPerformanceBuckets getBuckets() {
    return buckets;
  }


  @JsonProperty(value = JSON_PROPERTY_BUCKETS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBuckets(@javax.annotation.Nonnull MetricsPerformanceBuckets buckets) {
    this.buckets = buckets;
  }


  public MetricsPerformance complained(@javax.annotation.Nonnull Integer complained) {
    this.complained = complained;
    return this;
  }

  /**
   * Count of messages complained during the specified time range. 
   * minimum: 0
   * @return complained
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COMPLAINED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getComplained() {
    return complained;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPLAINED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setComplained(@javax.annotation.Nonnull Integer complained) {
    this.complained = complained;
  }


  public MetricsPerformance delivered(@javax.annotation.Nonnull Integer delivered) {
    this.delivered = delivered;
    return this;
  }

  /**
   * Count of messages delivered during the specified time range. 
   * minimum: 0
   * @return delivered
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DELIVERED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getDelivered() {
    return delivered;
  }


  @JsonProperty(value = JSON_PROPERTY_DELIVERED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDelivered(@javax.annotation.Nonnull Integer delivered) {
    this.delivered = delivered;
  }


  public MetricsPerformance endTime(@javax.annotation.Nullable OffsetDateTime endTime) {
    this.endTime = endTime;
    return this;
  }

  /**
   * The end of the time range for retrieving message performance metrics (exclusive).
   * @return endTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_END_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getEndTime() {
    return endTime;
  }


  @JsonProperty(value = JSON_PROPERTY_END_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndTime(@javax.annotation.Nullable OffsetDateTime endTime) {
    this.endTime = endTime;
  }


  public MetricsPerformance processed(@javax.annotation.Nonnull Integer processed) {
    this.processed = processed;
    return this;
  }

  /**
   * Count of messages processed during the specified time range. 
   * minimum: 0
   * @return processed
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROCESSED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getProcessed() {
    return processed;
  }


  @JsonProperty(value = JSON_PROPERTY_PROCESSED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProcessed(@javax.annotation.Nonnull Integer processed) {
    this.processed = processed;
  }


  public MetricsPerformance startTime(@javax.annotation.Nullable OffsetDateTime startTime) {
    this.startTime = startTime;
    return this;
  }

  /**
   * The beginning of the time range for retrieving message performance metrics (inclusive). 
   * @return startTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getStartTime() {
    return startTime;
  }


  @JsonProperty(value = JSON_PROPERTY_START_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(@javax.annotation.Nullable OffsetDateTime startTime) {
    this.startTime = startTime;
  }


  /**
   * Return true if this MetricsPerformance object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetricsPerformance metricsPerformance = (MetricsPerformance) o;
    return Objects.equals(this.bounced, metricsPerformance.bounced) &&
        Objects.equals(this.buckets, metricsPerformance.buckets) &&
        Objects.equals(this.complained, metricsPerformance.complained) &&
        Objects.equals(this.delivered, metricsPerformance.delivered) &&
        Objects.equals(this.endTime, metricsPerformance.endTime) &&
        Objects.equals(this.processed, metricsPerformance.processed) &&
        Objects.equals(this.startTime, metricsPerformance.startTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bounced, buckets, complained, delivered, endTime, processed, startTime);
  }

  @Override
  public String toString() {
    return "MetricsPerformance { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `bounced` to the URL query string
    if (getBounced() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbounced%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBounced()))));
    }

    // add `buckets` to the URL query string
    if (getBuckets() != null) {
      joiner.add(getBuckets().toUrlQueryString(prefix + "buckets" + suffix));
    }

    // add `complained` to the URL query string
    if (getComplained() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scomplained%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getComplained()))));
    }

    // add `delivered` to the URL query string
    if (getDelivered() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdelivered%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDelivered()))));
    }

    // add `end_time` to the URL query string
    if (getEndTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%send_time%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndTime()))));
    }

    // add `processed` to the URL query string
    if (getProcessed() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprocessed%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProcessed()))));
    }

    // add `start_time` to the URL query string
    if (getStartTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstart_time%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStartTime()))));
    }

    return joiner.toString();
  }
}

