/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.mailchannels.model.MetricsBucket;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * A series of metrics aggregations bucketed by time interval (e.g. hour, day)
 */
@JsonPropertyOrder({
  MetricsPerformanceBuckets.JSON_PROPERTY_BOUNCED,
  MetricsPerformanceBuckets.JSON_PROPERTY_COMPLAINED,
  MetricsPerformanceBuckets.JSON_PROPERTY_DELIVERED,
  MetricsPerformanceBuckets.JSON_PROPERTY_PROCESSED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class MetricsPerformanceBuckets {
  public static final String JSON_PROPERTY_BOUNCED = "bounced";
  @javax.annotation.Nonnull
  private List<MetricsBucket> bounced = new ArrayList<>();

  public static final String JSON_PROPERTY_COMPLAINED = "complained";
  @javax.annotation.Nonnull
  private List<MetricsBucket> complained = new ArrayList<>();

  public static final String JSON_PROPERTY_DELIVERED = "delivered";
  @javax.annotation.Nonnull
  private List<MetricsBucket> delivered = new ArrayList<>();

  public static final String JSON_PROPERTY_PROCESSED = "processed";
  @javax.annotation.Nonnull
  private List<MetricsBucket> processed = new ArrayList<>();

  public MetricsPerformanceBuckets() { 
  }

  public MetricsPerformanceBuckets bounced(@javax.annotation.Nonnull List<MetricsBucket> bounced) {
    this.bounced = bounced;
    return this;
  }

  public MetricsPerformanceBuckets addBouncedItem(MetricsBucket bouncedItem) {
    if (this.bounced == null) {
      this.bounced = new ArrayList<>();
    }
    this.bounced.add(bouncedItem);
    return this;
  }

  /**
   * Get bounced
   * @return bounced
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BOUNCED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<MetricsBucket> getBounced() {
    return bounced;
  }


  @JsonProperty(value = JSON_PROPERTY_BOUNCED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBounced(@javax.annotation.Nonnull List<MetricsBucket> bounced) {
    this.bounced = bounced;
  }


  public MetricsPerformanceBuckets complained(@javax.annotation.Nonnull List<MetricsBucket> complained) {
    this.complained = complained;
    return this;
  }

  public MetricsPerformanceBuckets addComplainedItem(MetricsBucket complainedItem) {
    if (this.complained == null) {
      this.complained = new ArrayList<>();
    }
    this.complained.add(complainedItem);
    return this;
  }

  /**
   * Get complained
   * @return complained
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COMPLAINED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<MetricsBucket> getComplained() {
    return complained;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPLAINED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setComplained(@javax.annotation.Nonnull List<MetricsBucket> complained) {
    this.complained = complained;
  }


  public MetricsPerformanceBuckets delivered(@javax.annotation.Nonnull List<MetricsBucket> delivered) {
    this.delivered = delivered;
    return this;
  }

  public MetricsPerformanceBuckets addDeliveredItem(MetricsBucket deliveredItem) {
    if (this.delivered == null) {
      this.delivered = new ArrayList<>();
    }
    this.delivered.add(deliveredItem);
    return this;
  }

  /**
   * Get delivered
   * @return delivered
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DELIVERED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<MetricsBucket> getDelivered() {
    return delivered;
  }


  @JsonProperty(value = JSON_PROPERTY_DELIVERED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDelivered(@javax.annotation.Nonnull List<MetricsBucket> delivered) {
    this.delivered = delivered;
  }


  public MetricsPerformanceBuckets processed(@javax.annotation.Nonnull List<MetricsBucket> processed) {
    this.processed = processed;
    return this;
  }

  public MetricsPerformanceBuckets addProcessedItem(MetricsBucket processedItem) {
    if (this.processed == null) {
      this.processed = new ArrayList<>();
    }
    this.processed.add(processedItem);
    return this;
  }

  /**
   * Get processed
   * @return processed
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROCESSED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<MetricsBucket> getProcessed() {
    return processed;
  }


  @JsonProperty(value = JSON_PROPERTY_PROCESSED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProcessed(@javax.annotation.Nonnull List<MetricsBucket> processed) {
    this.processed = processed;
  }


  /**
   * Return true if this MetricsPerformance_buckets object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetricsPerformanceBuckets metricsPerformanceBuckets = (MetricsPerformanceBuckets) o;
    return Objects.equals(this.bounced, metricsPerformanceBuckets.bounced) &&
        Objects.equals(this.complained, metricsPerformanceBuckets.complained) &&
        Objects.equals(this.delivered, metricsPerformanceBuckets.delivered) &&
        Objects.equals(this.processed, metricsPerformanceBuckets.processed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bounced, complained, delivered, processed);
  }

  @Override
  public String toString() {
    return "MetricsPerformanceBuckets { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `bounced` to the URL query string
    if (getBounced() != null) {
      for (int i = 0; i < getBounced().size(); i++) {
        if (getBounced().get(i) != null) {
          joiner.add(getBounced().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sbounced%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `complained` to the URL query string
    if (getComplained() != null) {
      for (int i = 0; i < getComplained().size(); i++) {
        if (getComplained().get(i) != null) {
          joiner.add(getComplained().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%scomplained%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `delivered` to the URL query string
    if (getDelivered() != null) {
      for (int i = 0; i < getDelivered().size(); i++) {
        if (getDelivered().get(i) != null) {
          joiner.add(getDelivered().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdelivered%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `processed` to the URL query string
    if (getProcessed() != null) {
      for (int i = 0; i < getProcessed().size(); i++) {
        if (getProcessed().get(i) != null) {
          joiner.add(getProcessed().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sprocessed%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

