/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * MetricsSender
 */
@JsonPropertyOrder({
  MetricsSender.JSON_PROPERTY_BOUNCED,
  MetricsSender.JSON_PROPERTY_DELIVERED,
  MetricsSender.JSON_PROPERTY_DROPPED,
  MetricsSender.JSON_PROPERTY_NAME,
  MetricsSender.JSON_PROPERTY_PROCESSED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class MetricsSender {
  public static final String JSON_PROPERTY_BOUNCED = "bounced";
  @javax.annotation.Nonnull
  private Integer bounced;

  public static final String JSON_PROPERTY_DELIVERED = "delivered";
  @javax.annotation.Nonnull
  private Integer delivered;

  public static final String JSON_PROPERTY_DROPPED = "dropped";
  @javax.annotation.Nonnull
  private Integer dropped;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_PROCESSED = "processed";
  @javax.annotation.Nonnull
  private Integer processed;

  public MetricsSender() { 
  }

  public MetricsSender bounced(@javax.annotation.Nonnull Integer bounced) {
    this.bounced = bounced;
    return this;
  }

  /**
   * Get bounced
   * minimum: 0
   * @return bounced
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BOUNCED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getBounced() {
    return bounced;
  }


  @JsonProperty(value = JSON_PROPERTY_BOUNCED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBounced(@javax.annotation.Nonnull Integer bounced) {
    this.bounced = bounced;
  }


  public MetricsSender delivered(@javax.annotation.Nonnull Integer delivered) {
    this.delivered = delivered;
    return this;
  }

  /**
   * Get delivered
   * minimum: 0
   * @return delivered
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DELIVERED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getDelivered() {
    return delivered;
  }


  @JsonProperty(value = JSON_PROPERTY_DELIVERED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDelivered(@javax.annotation.Nonnull Integer delivered) {
    this.delivered = delivered;
  }


  public MetricsSender dropped(@javax.annotation.Nonnull Integer dropped) {
    this.dropped = dropped;
    return this;
  }

  /**
   * Get dropped
   * minimum: 0
   * @return dropped
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DROPPED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getDropped() {
    return dropped;
  }


  @JsonProperty(value = JSON_PROPERTY_DROPPED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDropped(@javax.annotation.Nonnull Integer dropped) {
    this.dropped = dropped;
  }


  public MetricsSender name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public MetricsSender processed(@javax.annotation.Nonnull Integer processed) {
    this.processed = processed;
    return this;
  }

  /**
   * Get processed
   * minimum: 0
   * @return processed
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROCESSED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getProcessed() {
    return processed;
  }


  @JsonProperty(value = JSON_PROPERTY_PROCESSED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProcessed(@javax.annotation.Nonnull Integer processed) {
    this.processed = processed;
  }


  /**
   * Return true if this MetricsSender object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetricsSender metricsSender = (MetricsSender) o;
    return Objects.equals(this.bounced, metricsSender.bounced) &&
        Objects.equals(this.delivered, metricsSender.delivered) &&
        Objects.equals(this.dropped, metricsSender.dropped) &&
        Objects.equals(this.name, metricsSender.name) &&
        Objects.equals(this.processed, metricsSender.processed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bounced, delivered, dropped, name, processed);
  }

  @Override
  public String toString() {
    return "MetricsSender { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `bounced` to the URL query string
    if (getBounced() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbounced%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBounced()))));
    }

    // add `delivered` to the URL query string
    if (getDelivered() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdelivered%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDelivered()))));
    }

    // add `dropped` to the URL query string
    if (getDropped() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdropped%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDropped()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `processed` to the URL query string
    if (getProcessed() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprocessed%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProcessed()))));
    }

    return joiner.toString();
  }
}

