/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.mailchannels.model.EmailAddress;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * Personalization
 */
@JsonPropertyOrder({
  Personalization.JSON_PROPERTY_BCC,
  Personalization.JSON_PROPERTY_CC,
  Personalization.JSON_PROPERTY_DKIM_DOMAIN,
  Personalization.JSON_PROPERTY_DKIM_PRIVATE_KEY,
  Personalization.JSON_PROPERTY_DKIM_SELECTOR,
  Personalization.JSON_PROPERTY_DYNAMIC_TEMPLATE_DATA,
  Personalization.JSON_PROPERTY_ENVELOPE_FROM,
  Personalization.JSON_PROPERTY_FROM,
  Personalization.JSON_PROPERTY_HEADERS,
  Personalization.JSON_PROPERTY_REPLY_TO,
  Personalization.JSON_PROPERTY_SUBJECT,
  Personalization.JSON_PROPERTY_TO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class Personalization {
  public static final String JSON_PROPERTY_BCC = "bcc";
  @javax.annotation.Nullable
  private List<EmailAddress> bcc = new ArrayList<>();

  public static final String JSON_PROPERTY_CC = "cc";
  @javax.annotation.Nullable
  private List<EmailAddress> cc = new ArrayList<>();

  public static final String JSON_PROPERTY_DKIM_DOMAIN = "dkim_domain";
  @javax.annotation.Nullable
  private String dkimDomain;

  public static final String JSON_PROPERTY_DKIM_PRIVATE_KEY = "dkim_private_key";
  @javax.annotation.Nullable
  private String dkimPrivateKey;

  public static final String JSON_PROPERTY_DKIM_SELECTOR = "dkim_selector";
  @javax.annotation.Nullable
  private String dkimSelector;

  public static final String JSON_PROPERTY_DYNAMIC_TEMPLATE_DATA = "dynamic_template_data";
  @javax.annotation.Nullable
  private Object dynamicTemplateData;

  public static final String JSON_PROPERTY_ENVELOPE_FROM = "envelope_from";
  @javax.annotation.Nullable
  private EmailAddress envelopeFrom;

  public static final String JSON_PROPERTY_FROM = "from";
  @javax.annotation.Nullable
  private EmailAddress from;

  public static final String JSON_PROPERTY_HEADERS = "headers";
  @javax.annotation.Nullable
  private Map<String, String> headers = new HashMap<>();

  public static final String JSON_PROPERTY_REPLY_TO = "reply_to";
  @javax.annotation.Nullable
  private EmailAddress replyTo;

  public static final String JSON_PROPERTY_SUBJECT = "subject";
  @javax.annotation.Nullable
  private String subject;

  public static final String JSON_PROPERTY_TO = "to";
  @javax.annotation.Nonnull
  private List<EmailAddress> to = new ArrayList<>();

  public Personalization() { 
  }

  public Personalization bcc(@javax.annotation.Nullable List<EmailAddress> bcc) {
    this.bcc = bcc;
    return this;
  }

  public Personalization addBccItem(EmailAddress bccItem) {
    if (this.bcc == null) {
      this.bcc = new ArrayList<>();
    }
    this.bcc.add(bccItem);
    return this;
  }

  /**
   * Get bcc
   * @return bcc
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BCC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<EmailAddress> getBcc() {
    return bcc;
  }


  @JsonProperty(value = JSON_PROPERTY_BCC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBcc(@javax.annotation.Nullable List<EmailAddress> bcc) {
    this.bcc = bcc;
  }


  public Personalization cc(@javax.annotation.Nullable List<EmailAddress> cc) {
    this.cc = cc;
    return this;
  }

  public Personalization addCcItem(EmailAddress ccItem) {
    if (this.cc == null) {
      this.cc = new ArrayList<>();
    }
    this.cc.add(ccItem);
    return this;
  }

  /**
   * Get cc
   * @return cc
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<EmailAddress> getCc() {
    return cc;
  }


  @JsonProperty(value = JSON_PROPERTY_CC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCc(@javax.annotation.Nullable List<EmailAddress> cc) {
    this.cc = cc;
  }


  public Personalization dkimDomain(@javax.annotation.Nullable String dkimDomain) {
    this.dkimDomain = dkimDomain;
    return this;
  }

  /**
   * If set, you must also provide the matching dkim_selector. 
   * @return dkimDomain
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DKIM_DOMAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDkimDomain() {
    return dkimDomain;
  }


  @JsonProperty(value = JSON_PROPERTY_DKIM_DOMAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDkimDomain(@javax.annotation.Nullable String dkimDomain) {
    this.dkimDomain = dkimDomain;
  }


  public Personalization dkimPrivateKey(@javax.annotation.Nullable String dkimPrivateKey) {
    this.dkimPrivateKey = dkimPrivateKey;
    return this;
  }

  /**
   * Encoded in Base64. If set, you must also provide the matching dkim_domain and dkim_selector. 
   * @return dkimPrivateKey
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DKIM_PRIVATE_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDkimPrivateKey() {
    return dkimPrivateKey;
  }


  @JsonProperty(value = JSON_PROPERTY_DKIM_PRIVATE_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDkimPrivateKey(@javax.annotation.Nullable String dkimPrivateKey) {
    this.dkimPrivateKey = dkimPrivateKey;
  }


  public Personalization dkimSelector(@javax.annotation.Nullable String dkimSelector) {
    this.dkimSelector = dkimSelector;
    return this;
  }

  /**
   * If set without a matching dkim_domain, the domain will be taken from the &#x60;from&#x60; email address. 
   * @return dkimSelector
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DKIM_SELECTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDkimSelector() {
    return dkimSelector;
  }


  @JsonProperty(value = JSON_PROPERTY_DKIM_SELECTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDkimSelector(@javax.annotation.Nullable String dkimSelector) {
    this.dkimSelector = dkimSelector;
  }


  public Personalization dynamicTemplateData(@javax.annotation.Nullable Object dynamicTemplateData) {
    this.dynamicTemplateData = dynamicTemplateData;
    return this;
  }

  /**
   * A JSON object containing key-value pairs of variables to set for template rendering. Keys must be strings, and values can be one of the following types: * string * boolean * number * list, whose values are all of permitted types * map, whose keys must be strings, and whose values are all of permitted types 
   * @return dynamicTemplateData
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DYNAMIC_TEMPLATE_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Object getDynamicTemplateData() {
    return dynamicTemplateData;
  }


  @JsonProperty(value = JSON_PROPERTY_DYNAMIC_TEMPLATE_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDynamicTemplateData(@javax.annotation.Nullable Object dynamicTemplateData) {
    this.dynamicTemplateData = dynamicTemplateData;
  }


  public Personalization envelopeFrom(@javax.annotation.Nullable EmailAddress envelopeFrom) {
    this.envelopeFrom = envelopeFrom;
    return this;
  }

  /**
   * Get envelopeFrom
   * @return envelopeFrom
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENVELOPE_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EmailAddress getEnvelopeFrom() {
    return envelopeFrom;
  }


  @JsonProperty(value = JSON_PROPERTY_ENVELOPE_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnvelopeFrom(@javax.annotation.Nullable EmailAddress envelopeFrom) {
    this.envelopeFrom = envelopeFrom;
  }


  public Personalization from(@javax.annotation.Nullable EmailAddress from) {
    this.from = from;
    return this;
  }

  /**
   * Get from
   * @return from
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EmailAddress getFrom() {
    return from;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFrom(@javax.annotation.Nullable EmailAddress from) {
    this.from = from;
  }


  public Personalization headers(@javax.annotation.Nullable Map<String, String> headers) {
    this.headers = headers;
    return this;
  }

  public Personalization putHeadersItem(String key, String headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

  /**
   * A JSON object containing key-value pairs, where both keys (header names) and values must be strings. These pairs represent custom headers to be substituted. Please note the following restrictions and behavior: - Reserved headers: The following headers cannot be modified:   - Authentication-Results   - BCC   - CC   - Content-Transfer-Encoding   - Content-Type   - DKIM-Signature   - From   - Message-ID   - Received   - Reply-To   - Subject   - To - Header precedence: If a header is defined in both the personalizations object and the root headers, the value from personalizations will be used. - Case sensitivity: Headers are treated as case-insensitive. If multiple headers differ only by case, only one will be used, with no guarantee of which one. 
   * @return headers
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, String> getHeaders() {
    return headers;
  }


  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeaders(@javax.annotation.Nullable Map<String, String> headers) {
    this.headers = headers;
  }


  public Personalization replyTo(@javax.annotation.Nullable EmailAddress replyTo) {
    this.replyTo = replyTo;
    return this;
  }

  /**
   * Get replyTo
   * @return replyTo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REPLY_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EmailAddress getReplyTo() {
    return replyTo;
  }


  @JsonProperty(value = JSON_PROPERTY_REPLY_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplyTo(@javax.annotation.Nullable EmailAddress replyTo) {
    this.replyTo = replyTo;
  }


  public Personalization subject(@javax.annotation.Nullable String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * Get subject
   * @return subject
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSubject() {
    return subject;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubject(@javax.annotation.Nullable String subject) {
    this.subject = subject;
  }


  public Personalization to(@javax.annotation.Nonnull List<EmailAddress> to) {
    this.to = to;
    return this;
  }

  public Personalization addToItem(EmailAddress toItem) {
    if (this.to == null) {
      this.to = new ArrayList<>();
    }
    this.to.add(toItem);
    return this;
  }

  /**
   * Get to
   * @return to
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<EmailAddress> getTo() {
    return to;
  }


  @JsonProperty(value = JSON_PROPERTY_TO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTo(@javax.annotation.Nonnull List<EmailAddress> to) {
    this.to = to;
  }


  /**
   * Return true if this Personalization object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Personalization personalization = (Personalization) o;
    return Objects.equals(this.bcc, personalization.bcc) &&
        Objects.equals(this.cc, personalization.cc) &&
        Objects.equals(this.dkimDomain, personalization.dkimDomain) &&
        Objects.equals(this.dkimPrivateKey, personalization.dkimPrivateKey) &&
        Objects.equals(this.dkimSelector, personalization.dkimSelector) &&
        Objects.equals(this.dynamicTemplateData, personalization.dynamicTemplateData) &&
        Objects.equals(this.envelopeFrom, personalization.envelopeFrom) &&
        Objects.equals(this.from, personalization.from) &&
        Objects.equals(this.headers, personalization.headers) &&
        Objects.equals(this.replyTo, personalization.replyTo) &&
        Objects.equals(this.subject, personalization.subject) &&
        Objects.equals(this.to, personalization.to);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bcc, cc, dkimDomain, dkimPrivateKey, dkimSelector, dynamicTemplateData, envelopeFrom, from, headers, replyTo, subject, to);
  }

  @Override
  public String toString() {
    return "Personalization { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `bcc` to the URL query string
    if (getBcc() != null) {
      for (int i = 0; i < getBcc().size(); i++) {
        if (getBcc().get(i) != null) {
          joiner.add(getBcc().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sbcc%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `cc` to the URL query string
    if (getCc() != null) {
      for (int i = 0; i < getCc().size(); i++) {
        if (getCc().get(i) != null) {
          joiner.add(getCc().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%scc%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `dkim_domain` to the URL query string
    if (getDkimDomain() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdkim_domain%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDkimDomain()))));
    }

    // add `dkim_private_key` to the URL query string
    if (getDkimPrivateKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdkim_private_key%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDkimPrivateKey()))));
    }

    // add `dkim_selector` to the URL query string
    if (getDkimSelector() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdkim_selector%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDkimSelector()))));
    }

    // add `dynamic_template_data` to the URL query string
    if (getDynamicTemplateData() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdynamic_template_data%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDynamicTemplateData()))));
    }

    // add `envelope_from` to the URL query string
    if (getEnvelopeFrom() != null) {
      joiner.add(getEnvelopeFrom().toUrlQueryString(prefix + "envelope_from" + suffix));
    }

    // add `from` to the URL query string
    if (getFrom() != null) {
      joiner.add(getFrom().toUrlQueryString(prefix + "from" + suffix));
    }

    // add `headers` to the URL query string
    if (getHeaders() != null) {
      for (String _key : getHeaders().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sheaders%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getHeaders().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getHeaders().get(_key)))));
      }
    }

    // add `reply_to` to the URL query string
    if (getReplyTo() != null) {
      joiner.add(getReplyTo().toUrlQueryString(prefix + "reply_to" + suffix));
    }

    // add `subject` to the URL query string
    if (getSubject() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubject()))));
    }

    // add `to` to the URL query string
    if (getTo() != null) {
      for (int i = 0; i < getTo().size(); i++) {
        if (getTo().get(i) != null) {
          joiner.add(getTo().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sto%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

