/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.mailchannels.model.SenderDomainResultA;
import com.mailchannels.model.SenderDomainResultMx;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * These results are here to help avoid SDNF (Sender Domain Not Found) blocks. For messages not to get blocked by [SDNF](https://support.mailchannels.com/hc/en-us/articles/203155500-550-5-2-1-SDNF-Sender-Domain-Not-Found), we require either an MX or A record to exist for the sender domain. 
 */
@JsonPropertyOrder({
  SenderDomainResult.JSON_PROPERTY_A,
  SenderDomainResult.JSON_PROPERTY_MX,
  SenderDomainResult.JSON_PROPERTY_VERDICT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class SenderDomainResult {
  public static final String JSON_PROPERTY_A = "a";
  @javax.annotation.Nullable
  private SenderDomainResultA a;

  public static final String JSON_PROPERTY_MX = "mx";
  @javax.annotation.Nullable
  private SenderDomainResultMx mx;

  /**
   * Overall verdict. Passed if either A or MX record check passed.
   */
  public enum VerdictEnum {
    PASSED(String.valueOf("passed")),
    
    FAILED(String.valueOf("failed"));

    private String value;

    VerdictEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VerdictEnum fromValue(String value) {
      for (VerdictEnum b : VerdictEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_VERDICT = "verdict";
  @javax.annotation.Nullable
  private VerdictEnum verdict;

  public SenderDomainResult() { 
  }

  public SenderDomainResult a(@javax.annotation.Nullable SenderDomainResultA a) {
    this.a = a;
    return this;
  }

  /**
   * Get a
   * @return a
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_A, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SenderDomainResultA getA() {
    return a;
  }


  @JsonProperty(value = JSON_PROPERTY_A, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setA(@javax.annotation.Nullable SenderDomainResultA a) {
    this.a = a;
  }


  public SenderDomainResult mx(@javax.annotation.Nullable SenderDomainResultMx mx) {
    this.mx = mx;
    return this;
  }

  /**
   * Get mx
   * @return mx
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SenderDomainResultMx getMx() {
    return mx;
  }


  @JsonProperty(value = JSON_PROPERTY_MX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMx(@javax.annotation.Nullable SenderDomainResultMx mx) {
    this.mx = mx;
  }


  public SenderDomainResult verdict(@javax.annotation.Nullable VerdictEnum verdict) {
    this.verdict = verdict;
    return this;
  }

  /**
   * Overall verdict. Passed if either A or MX record check passed.
   * @return verdict
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERDICT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public VerdictEnum getVerdict() {
    return verdict;
  }


  @JsonProperty(value = JSON_PROPERTY_VERDICT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVerdict(@javax.annotation.Nullable VerdictEnum verdict) {
    this.verdict = verdict;
  }


  /**
   * Return true if this SenderDomainResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SenderDomainResult senderDomainResult = (SenderDomainResult) o;
    return Objects.equals(this.a, senderDomainResult.a) &&
        Objects.equals(this.mx, senderDomainResult.mx) &&
        Objects.equals(this.verdict, senderDomainResult.verdict);
  }

  @Override
  public int hashCode() {
    return Objects.hash(a, mx, verdict);
  }

  @Override
  public String toString() {
    return "SenderDomainResult { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `a` to the URL query string
    if (getA() != null) {
      joiner.add(getA().toUrlQueryString(prefix + "a" + suffix));
    }

    // add `mx` to the URL query string
    if (getMx() != null) {
      joiner.add(getMx().toUrlQueryString(prefix + "mx" + suffix));
    }

    // add `verdict` to the URL query string
    if (getVerdict() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sverdict%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVerdict()))));
    }

    return joiner.toString();
  }
}

