/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * SubAccountData
 */
@JsonPropertyOrder({
  SubAccountData.JSON_PROPERTY_COMPANY_NAME,
  SubAccountData.JSON_PROPERTY_HANDLE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class SubAccountData {
  public static final String JSON_PROPERTY_COMPANY_NAME = "company_name";
  @javax.annotation.Nonnull
  private String companyName;

  public static final String JSON_PROPERTY_HANDLE = "handle";
  @javax.annotation.Nullable
  private String handle;

  public SubAccountData() { 
  }

  public SubAccountData companyName(@javax.annotation.Nonnull String companyName) {
    this.companyName = companyName;
    return this;
  }

  /**
   * The name of the company associated with the sub-account. This name is used for display purposes only and does not affect the functionality of the sub-account. The length must be between 3 and 128 characters. 
   * @return companyName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COMPANY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCompanyName() {
    return companyName;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPANY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCompanyName(@javax.annotation.Nonnull String companyName) {
    this.companyName = companyName;
  }


  public SubAccountData handle(@javax.annotation.Nullable String handle) {
    this.handle = handle;
    return this;
  }

  /**
   * A unique name for the sub-account to be created. The length must be between 3 and 128 characters, and it may contain only lowercase letters and numbers. If not provided, a random handle will be generated. 
   * @return handle
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HANDLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHandle() {
    return handle;
  }


  @JsonProperty(value = JSON_PROPERTY_HANDLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHandle(@javax.annotation.Nullable String handle) {
    this.handle = handle;
  }


  /**
   * Return true if this SubAccountData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubAccountData subAccountData = (SubAccountData) o;
    return Objects.equals(this.companyName, subAccountData.companyName) &&
        Objects.equals(this.handle, subAccountData.handle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyName, handle);
  }

  @Override
  public String toString() {
    return "SubAccountData { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `company_name` to the URL query string
    if (getCompanyName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scompany_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCompanyName()))));
    }

    // add `handle` to the URL query string
    if (getHandle() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shandle%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHandle()))));
    }

    return joiner.toString();
  }
}

