/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.mailchannels.model.SuppressionEntry;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * SuppressionListInput
 */
@JsonPropertyOrder({
  SuppressionListInput.JSON_PROPERTY_ADD_TO_SUB_ACCOUNTS,
  SuppressionListInput.JSON_PROPERTY_SUPPRESSION_ENTRIES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class SuppressionListInput {
  public static final String JSON_PROPERTY_ADD_TO_SUB_ACCOUNTS = "add_to_sub_accounts";
  @javax.annotation.Nullable
  private Boolean addToSubAccounts = false;

  public static final String JSON_PROPERTY_SUPPRESSION_ENTRIES = "suppression_entries";
  @javax.annotation.Nonnull
  private List<SuppressionEntry> suppressionEntries = new ArrayList<>();

  public SuppressionListInput() { 
  }

  public SuppressionListInput addToSubAccounts(@javax.annotation.Nullable Boolean addToSubAccounts) {
    this.addToSubAccounts = addToSubAccounts;
    return this;
  }

  /**
   * If true, the parent account creates suppression entries for all associated sub-accounts. This field is only applicable to parent accounts. Sub-accounts cannot create entries for other sub-accounts. 
   * @return addToSubAccounts
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADD_TO_SUB_ACCOUNTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getAddToSubAccounts() {
    return addToSubAccounts;
  }


  @JsonProperty(value = JSON_PROPERTY_ADD_TO_SUB_ACCOUNTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddToSubAccounts(@javax.annotation.Nullable Boolean addToSubAccounts) {
    this.addToSubAccounts = addToSubAccounts;
  }


  public SuppressionListInput suppressionEntries(@javax.annotation.Nonnull List<SuppressionEntry> suppressionEntries) {
    this.suppressionEntries = suppressionEntries;
    return this;
  }

  public SuppressionListInput addSuppressionEntriesItem(SuppressionEntry suppressionEntriesItem) {
    if (this.suppressionEntries == null) {
      this.suppressionEntries = new ArrayList<>();
    }
    this.suppressionEntries.add(suppressionEntriesItem);
    return this;
  }

  /**
   * The total number of suppression entries to create, for the parent and/or its sub-accounts, must not exceed 1000.
   * @return suppressionEntries
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUPPRESSION_ENTRIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<SuppressionEntry> getSuppressionEntries() {
    return suppressionEntries;
  }


  @JsonProperty(value = JSON_PROPERTY_SUPPRESSION_ENTRIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSuppressionEntries(@javax.annotation.Nonnull List<SuppressionEntry> suppressionEntries) {
    this.suppressionEntries = suppressionEntries;
  }


  /**
   * Return true if this SuppressionListInput object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SuppressionListInput suppressionListInput = (SuppressionListInput) o;
    return Objects.equals(this.addToSubAccounts, suppressionListInput.addToSubAccounts) &&
        Objects.equals(this.suppressionEntries, suppressionListInput.suppressionEntries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addToSubAccounts, suppressionEntries);
  }

  @Override
  public String toString() {
    return "SuppressionListInput { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `add_to_sub_accounts` to the URL query string
    if (getAddToSubAccounts() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sadd_to_sub_accounts%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAddToSubAccounts()))));
    }

    // add `suppression_entries` to the URL query string
    if (getSuppressionEntries() != null) {
      for (int i = 0; i < getSuppressionEntries().size(); i++) {
        if (getSuppressionEntries().get(i) != null) {
          joiner.add(getSuppressionEntries().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%ssuppression_entries%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

