/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * Webhook
 */
@JsonPropertyOrder({
  Webhook.JSON_PROPERTY_WEBHOOK
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class Webhook {
  public static final String JSON_PROPERTY_WEBHOOK = "webhook";
  @javax.annotation.Nonnull
  private String webhook;

  public Webhook() { 
  }

  public Webhook webhook(@javax.annotation.Nonnull String webhook) {
    this.webhook = webhook;
    return this;
  }

  /**
   * A customer&#39;s webhook that events will be sent to
   * @return webhook
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_WEBHOOK, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getWebhook() {
    return webhook;
  }


  @JsonProperty(value = JSON_PROPERTY_WEBHOOK, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWebhook(@javax.annotation.Nonnull String webhook) {
    this.webhook = webhook;
  }


  /**
   * Return true if this Webhook object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Webhook webhook = (Webhook) o;
    return Objects.equals(this.webhook, webhook.webhook);
  }

  @Override
  public int hashCode() {
    return Objects.hash(webhook);
  }

  @Override
  public String toString() {
    return "Webhook { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `webhook` to the URL query string
    if (getWebhook() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swebhook%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWebhook()))));
    }

    return joiner.toString();
  }
}

