/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * WebhookResendResponse
 */
@JsonPropertyOrder({
  WebhookResendResponse.JSON_PROPERTY_BATCH_ID,
  WebhookResendResponse.JSON_PROPERTY_CREATED_AT,
  WebhookResendResponse.JSON_PROPERTY_CUSTOMER_HANDLE,
  WebhookResendResponse.JSON_PROPERTY_DURATION_IN_MS,
  WebhookResendResponse.JSON_PROPERTY_EVENT_COUNT,
  WebhookResendResponse.JSON_PROPERTY_STATUS_CODE,
  WebhookResendResponse.JSON_PROPERTY_WEBHOOK
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class WebhookResendResponse {
  public static final String JSON_PROPERTY_BATCH_ID = "batch_id";
  @javax.annotation.Nonnull
  private Long batchId;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_CUSTOMER_HANDLE = "customer_handle";
  @javax.annotation.Nonnull
  private String customerHandle;

  public static final String JSON_PROPERTY_DURATION_IN_MS = "duration_in_ms";
  private JsonNullable<Integer> durationInMs = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_EVENT_COUNT = "event_count";
  @javax.annotation.Nonnull
  private Integer eventCount;

  public static final String JSON_PROPERTY_STATUS_CODE = "status_code";
  private JsonNullable<Integer> statusCode = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_WEBHOOK = "webhook";
  @javax.annotation.Nonnull
  private String webhook;

  public WebhookResendResponse() { 
  }

  public WebhookResendResponse batchId(@javax.annotation.Nonnull Long batchId) {
    this.batchId = batchId;
    return this;
  }

  /**
   * Unique identifier for the webhook batch 
   * minimum: 0
   * @return batchId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BATCH_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getBatchId() {
    return batchId;
  }


  @JsonProperty(value = JSON_PROPERTY_BATCH_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBatchId(@javax.annotation.Nonnull Long batchId) {
    this.batchId = batchId;
  }


  public WebhookResendResponse createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Timestamp of when the webhook batch was created
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public WebhookResendResponse customerHandle(@javax.annotation.Nonnull String customerHandle) {
    this.customerHandle = customerHandle;
    return this;
  }

  /**
   * Customer handle associated with the webhook batch
   * @return customerHandle
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_HANDLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCustomerHandle() {
    return customerHandle;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_HANDLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCustomerHandle(@javax.annotation.Nonnull String customerHandle) {
    this.customerHandle = customerHandle;
  }


  public WebhookResendResponse durationInMs(@javax.annotation.Nullable Integer durationInMs) {
    this.durationInMs = JsonNullable.<Integer>of(durationInMs);
    return this;
  }

  /**
   * Duration of the webhook batch in milliseconds, measured from the time the request was sent to the webhook endpoint until the response was received. Null indicates that no response was returned from the webhook endpoint. 
   * minimum: 0
   * @return durationInMs
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Integer getDurationInMs() {
        return durationInMs.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DURATION_IN_MS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getDurationInMs_JsonNullable() {
    return durationInMs;
  }
  
  @JsonProperty(JSON_PROPERTY_DURATION_IN_MS)
  public void setDurationInMs_JsonNullable(JsonNullable<Integer> durationInMs) {
    this.durationInMs = durationInMs;
  }

  public void setDurationInMs(@javax.annotation.Nullable Integer durationInMs) {
    this.durationInMs = JsonNullable.<Integer>of(durationInMs);
  }


  public WebhookResendResponse eventCount(@javax.annotation.Nonnull Integer eventCount) {
    this.eventCount = eventCount;
    return this;
  }

  /**
   * Number of events in the webhook batch
   * minimum: 0
   * @return eventCount
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EVENT_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getEventCount() {
    return eventCount;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENT_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEventCount(@javax.annotation.Nonnull Integer eventCount) {
    this.eventCount = eventCount;
  }


  public WebhookResendResponse statusCode(@javax.annotation.Nullable Integer statusCode) {
    this.statusCode = JsonNullable.<Integer>of(statusCode);
    return this;
  }

  /**
   * HTTP status code returned by the webhook endpoint. Valid values are 100-599. Null indicates that no response was returned from the webhook endpoint. 
   * maximum: 599
   * @return statusCode
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Integer getStatusCode() {
        return statusCode.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_STATUS_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getStatusCode_JsonNullable() {
    return statusCode;
  }
  
  @JsonProperty(JSON_PROPERTY_STATUS_CODE)
  public void setStatusCode_JsonNullable(JsonNullable<Integer> statusCode) {
    this.statusCode = statusCode;
  }

  public void setStatusCode(@javax.annotation.Nullable Integer statusCode) {
    this.statusCode = JsonNullable.<Integer>of(statusCode);
  }


  public WebhookResendResponse webhook(@javax.annotation.Nonnull String webhook) {
    this.webhook = webhook;
    return this;
  }

  /**
   * Webhook URL to which events in the batch were posted
   * @return webhook
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_WEBHOOK, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getWebhook() {
    return webhook;
  }


  @JsonProperty(value = JSON_PROPERTY_WEBHOOK, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWebhook(@javax.annotation.Nonnull String webhook) {
    this.webhook = webhook;
  }


  /**
   * Return true if this WebhookResendResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookResendResponse webhookResendResponse = (WebhookResendResponse) o;
    return Objects.equals(this.batchId, webhookResendResponse.batchId) &&
        Objects.equals(this.createdAt, webhookResendResponse.createdAt) &&
        Objects.equals(this.customerHandle, webhookResendResponse.customerHandle) &&
        equalsNullable(this.durationInMs, webhookResendResponse.durationInMs) &&
        Objects.equals(this.eventCount, webhookResendResponse.eventCount) &&
        equalsNullable(this.statusCode, webhookResendResponse.statusCode) &&
        Objects.equals(this.webhook, webhookResendResponse.webhook);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(batchId, createdAt, customerHandle, hashCodeNullable(durationInMs), eventCount, hashCodeNullable(statusCode), webhook);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    return "WebhookResendResponse { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `batch_id` to the URL query string
    if (getBatchId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbatch_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBatchId()))));
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `customer_handle` to the URL query string
    if (getCustomerHandle() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scustomer_handle%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCustomerHandle()))));
    }

    // add `duration_in_ms` to the URL query string
    if (getDurationInMs() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sduration_in_ms%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDurationInMs()))));
    }

    // add `event_count` to the URL query string
    if (getEventCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sevent_count%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEventCount()))));
    }

    // add `status_code` to the URL query string
    if (getStatusCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus_code%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatusCode()))));
    }

    // add `webhook` to the URL query string
    if (getWebhook() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swebhook%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWebhook()))));
    }

    return joiner.toString();
  }
}

