/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.mailchannels.model.WebhookResponse;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * WebhookValidationResult
 */
@JsonPropertyOrder({
  WebhookValidationResult.JSON_PROPERTY_RESPONSE,
  WebhookValidationResult.JSON_PROPERTY_RESULT,
  WebhookValidationResult.JSON_PROPERTY_WEBHOOK
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class WebhookValidationResult {
  public static final String JSON_PROPERTY_RESPONSE = "response";
  @javax.annotation.Nullable
  private WebhookResponse response;

  /**
   * Indicates whether the webhook responded with a 2xx HTTP status code 
   */
  public enum ResultEnum {
    PASSED(String.valueOf("passed")),
    
    FAILED(String.valueOf("failed"));

    private String value;

    ResultEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ResultEnum fromValue(String value) {
      for (ResultEnum b : ResultEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_RESULT = "result";
  @javax.annotation.Nonnull
  private ResultEnum result;

  public static final String JSON_PROPERTY_WEBHOOK = "webhook";
  @javax.annotation.Nonnull
  private String webhook;

  public WebhookValidationResult() { 
  }

  public WebhookValidationResult response(@javax.annotation.Nullable WebhookResponse response) {
    this.response = response;
    return this;
  }

  /**
   * Get response
   * @return response
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESPONSE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public WebhookResponse getResponse() {
    return response;
  }


  @JsonProperty(value = JSON_PROPERTY_RESPONSE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResponse(@javax.annotation.Nullable WebhookResponse response) {
    this.response = response;
  }


  public WebhookValidationResult result(@javax.annotation.Nonnull ResultEnum result) {
    this.result = result;
    return this;
  }

  /**
   * Indicates whether the webhook responded with a 2xx HTTP status code 
   * @return result
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RESULT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ResultEnum getResult() {
    return result;
  }


  @JsonProperty(value = JSON_PROPERTY_RESULT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResult(@javax.annotation.Nonnull ResultEnum result) {
    this.result = result;
  }


  public WebhookValidationResult webhook(@javax.annotation.Nonnull String webhook) {
    this.webhook = webhook;
    return this;
  }

  /**
   * The webhook that was validated 
   * @return webhook
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_WEBHOOK, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getWebhook() {
    return webhook;
  }


  @JsonProperty(value = JSON_PROPERTY_WEBHOOK, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWebhook(@javax.annotation.Nonnull String webhook) {
    this.webhook = webhook;
  }


  /**
   * Return true if this WebhookValidationResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookValidationResult webhookValidationResult = (WebhookValidationResult) o;
    return Objects.equals(this.response, webhookValidationResult.response) &&
        Objects.equals(this.result, webhookValidationResult.result) &&
        Objects.equals(this.webhook, webhookValidationResult.webhook);
  }

  @Override
  public int hashCode() {
    return Objects.hash(response, result, webhook);
  }

  @Override
  public String toString() {
    return "WebhookValidationResult { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `response` to the URL query string
    if (getResponse() != null) {
      joiner.add(getResponse().toUrlQueryString(prefix + "response" + suffix));
    }

    // add `result` to the URL query string
    if (getResult() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sresult%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResult()))));
    }

    // add `webhook` to the URL query string
    if (getWebhook() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swebhook%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWebhook()))));
    }

    return joiner.toString();
  }
}

