/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailchannels.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.mailchannels.client.ApiClient;
/**
 * Duration of the webhook batch. measured from the time the request was sent to the webhook endpoint until the response was received. 
 */
@JsonPropertyOrder({
  WebhookBatchDuration.JSON_PROPERTY_UNIT,
  WebhookBatchDuration.JSON_PROPERTY_VALUE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class WebhookBatchDuration {
  /**
   * Gets or Sets unit
   */
  public enum UnitEnum {
    MILLISECONDS(String.valueOf("milliseconds"));

    private String value;

    UnitEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static UnitEnum fromValue(String value) {
      for (UnitEnum b : UnitEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_UNIT = "unit";
  @javax.annotation.Nonnull
  private UnitEnum unit;

  public static final String JSON_PROPERTY_VALUE = "value";
  @javax.annotation.Nonnull
  private Integer value;

  public WebhookBatchDuration() { 
  }

  public WebhookBatchDuration unit(@javax.annotation.Nonnull UnitEnum unit) {
    this.unit = unit;
    return this;
  }

  /**
   * Get unit
   * @return unit
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UNIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UnitEnum getUnit() {
    return unit;
  }


  @JsonProperty(value = JSON_PROPERTY_UNIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUnit(@javax.annotation.Nonnull UnitEnum unit) {
    this.unit = unit;
  }


  public WebhookBatchDuration value(@javax.annotation.Nonnull Integer value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * minimum: 0
   * @return value
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VALUE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getValue() {
    return value;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValue(@javax.annotation.Nonnull Integer value) {
    this.value = value;
  }


  /**
   * Return true if this WebhookBatchDuration object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookBatchDuration webhookBatchDuration = (WebhookBatchDuration) o;
    return Objects.equals(this.unit, webhookBatchDuration.unit) &&
        Objects.equals(this.value, webhookBatchDuration.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unit, value);
  }

  @Override
  public String toString() {
    return "WebhookBatchDuration { [REDACTED] }";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `unit` to the URL query string
    if (getUnit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sunit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUnit()))));
    }

    // add `value` to the URL query string
    if (getValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svalue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getValue()))));
    }

    return joiner.toString();
  }
}

