/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.mailchannels.api;

import com.mailchannels.model.CreateTrackingResult;
import com.mailchannels.model.UpdateTrackingResult;
import com.mailchannels.client.ApiClient;
import com.mailchannels.client.ApiException;
import com.mailchannels.client.ApiResponse;
import com.mailchannels.client.Configuration;
import com.mailchannels.client.Pair;

import com.mailchannels.model.CustomTrackingDomain;
import com.mailchannels.model.CustomTrackingDomainListResponse;
import com.mailchannels.model.DnsSetupRequired;
import com.mailchannels.model.ErrorResponse;
import com.mailchannels.model.PatchCustomTrackingDomainRequest;
import com.mailchannels.model.PostCustomTrackingDomainRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class CustomTrackingApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public CustomTrackingApi() {
    this(Configuration.getDefaultApiClient());
  }

  public CustomTrackingApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Register Custom Tracking Domain
   * Register a custom branded domain for click tracking, open tracking, or unsubscribe handling. By default, MailChannels uses shared domains for these links. Using a custom domain improves brand consistency by replacing shared domains with your own (e.g., click.example.com). Once registered, select the domain at send time using its &#x60;name&#x60;.  Before registration completes, two DNS records must be in place: 1. A TXT record at &#x60;_mailchannels-verify.&lt;hostname&gt;&#x60; containing the verification token    (returned in the 202 response). 2. A CNAME record at &#x60;&lt;hostname&gt;&#x60; pointing to &#x60;links.mailchannels.net&#x60;. 
   * @param xApiKey  (required)
   * @param postCustomTrackingDomainRequest  (required)
   * @return CreateTrackingResult
   * @throws ApiException if fails to make API call
   */
  public CreateTrackingResult createCustomTrackingDomain(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull PostCustomTrackingDomainRequest postCustomTrackingDomainRequest) throws ApiException {
    return createCustomTrackingDomain(xApiKey, postCustomTrackingDomainRequest, null);
  }

  /**
   * Register Custom Tracking Domain
   * Register a custom branded domain for click tracking, open tracking, or unsubscribe handling. By default, MailChannels uses shared domains for these links. Using a custom domain improves brand consistency by replacing shared domains with your own (e.g., click.example.com). Once registered, select the domain at send time using its &#x60;name&#x60;.  Before registration completes, two DNS records must be in place: 1. A TXT record at &#x60;_mailchannels-verify.&lt;hostname&gt;&#x60; containing the verification token    (returned in the 202 response). 2. A CNAME record at &#x60;&lt;hostname&gt;&#x60; pointing to &#x60;links.mailchannels.net&#x60;. 
   * @param xApiKey  (required)
   * @param postCustomTrackingDomainRequest  (required)
   * @param headers Optional headers to include in the request
   * @return CreateTrackingResult
   * @throws ApiException if fails to make API call
   */
  public CreateTrackingResult createCustomTrackingDomain(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull PostCustomTrackingDomainRequest postCustomTrackingDomainRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateTrackingResult> localVarResponse = createCustomTrackingDomainWithHttpInfo(xApiKey, postCustomTrackingDomainRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Register Custom Tracking Domain
   * Register a custom branded domain for click tracking, open tracking, or unsubscribe handling. By default, MailChannels uses shared domains for these links. Using a custom domain improves brand consistency by replacing shared domains with your own (e.g., click.example.com). Once registered, select the domain at send time using its &#x60;name&#x60;.  Before registration completes, two DNS records must be in place: 1. A TXT record at &#x60;_mailchannels-verify.&lt;hostname&gt;&#x60; containing the verification token    (returned in the 202 response). 2. A CNAME record at &#x60;&lt;hostname&gt;&#x60; pointing to &#x60;links.mailchannels.net&#x60;. 
   * @param xApiKey  (required)
   * @param postCustomTrackingDomainRequest  (required)
   * @return ApiResponse&lt;CreateTrackingResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateTrackingResult> createCustomTrackingDomainWithHttpInfo(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull PostCustomTrackingDomainRequest postCustomTrackingDomainRequest) throws ApiException {
    return createCustomTrackingDomainWithHttpInfo(xApiKey, postCustomTrackingDomainRequest, null);
  }

  /**
   * Register Custom Tracking Domain
   * Register a custom branded domain for click tracking, open tracking, or unsubscribe handling. By default, MailChannels uses shared domains for these links. Using a custom domain improves brand consistency by replacing shared domains with your own (e.g., click.example.com). Once registered, select the domain at send time using its &#x60;name&#x60;.  Before registration completes, two DNS records must be in place: 1. A TXT record at &#x60;_mailchannels-verify.&lt;hostname&gt;&#x60; containing the verification token    (returned in the 202 response). 2. A CNAME record at &#x60;&lt;hostname&gt;&#x60; pointing to &#x60;links.mailchannels.net&#x60;. 
   * @param xApiKey  (required)
   * @param postCustomTrackingDomainRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateTrackingResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateTrackingResult> createCustomTrackingDomainWithHttpInfo(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull PostCustomTrackingDomainRequest postCustomTrackingDomainRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createCustomTrackingDomainRequestBuilder(xApiKey, postCustomTrackingDomainRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createCustomTrackingDomain", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateTrackingResult>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8);
        CreateTrackingResult responseValue = CreateTrackingResult.decode(localVarResponse.statusCode(), responseBody, memberVarObjectMapper);
        

        return new ApiResponse<CreateTrackingResult>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createCustomTrackingDomainRequestBuilder(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull PostCustomTrackingDomainRequest postCustomTrackingDomainRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling createCustomTrackingDomain");
    }
    // verify the required parameter 'postCustomTrackingDomainRequest' is set
    if (postCustomTrackingDomainRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'postCustomTrackingDomainRequest' when calling createCustomTrackingDomain");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/custom-tracking-domains";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(postCustomTrackingDomainRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete Custom Tracking Domain
   * Permanently delete an existing custom tracking domain for the given hostname and scope. The domain can be re-registered if needed. WARNING: Any tracking links or unsubscribe URLs in previously sent emails using this domain will stop working immediately. 
   * @param hostname  (required)
   * @param scope  (required)
   * @param xApiKey  (required)
   * @throws ApiException if fails to make API call
   */
  public void deleteCustomTrackingDomain(@javax.annotation.Nonnull String hostname, @javax.annotation.Nonnull String scope, @javax.annotation.Nonnull String xApiKey) throws ApiException {
    deleteCustomTrackingDomain(hostname, scope, xApiKey, null);
  }

  /**
   * Delete Custom Tracking Domain
   * Permanently delete an existing custom tracking domain for the given hostname and scope. The domain can be re-registered if needed. WARNING: Any tracking links or unsubscribe URLs in previously sent emails using this domain will stop working immediately. 
   * @param hostname  (required)
   * @param scope  (required)
   * @param xApiKey  (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void deleteCustomTrackingDomain(@javax.annotation.Nonnull String hostname, @javax.annotation.Nonnull String scope, @javax.annotation.Nonnull String xApiKey, Map<String, String> headers) throws ApiException {
    deleteCustomTrackingDomainWithHttpInfo(hostname, scope, xApiKey, headers);
  }

  /**
   * Delete Custom Tracking Domain
   * Permanently delete an existing custom tracking domain for the given hostname and scope. The domain can be re-registered if needed. WARNING: Any tracking links or unsubscribe URLs in previously sent emails using this domain will stop working immediately. 
   * @param hostname  (required)
   * @param scope  (required)
   * @param xApiKey  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteCustomTrackingDomainWithHttpInfo(@javax.annotation.Nonnull String hostname, @javax.annotation.Nonnull String scope, @javax.annotation.Nonnull String xApiKey) throws ApiException {
    return deleteCustomTrackingDomainWithHttpInfo(hostname, scope, xApiKey, null);
  }

  /**
   * Delete Custom Tracking Domain
   * Permanently delete an existing custom tracking domain for the given hostname and scope. The domain can be re-registered if needed. WARNING: Any tracking links or unsubscribe URLs in previously sent emails using this domain will stop working immediately. 
   * @param hostname  (required)
   * @param scope  (required)
   * @param xApiKey  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteCustomTrackingDomainWithHttpInfo(@javax.annotation.Nonnull String hostname, @javax.annotation.Nonnull String scope, @javax.annotation.Nonnull String xApiKey, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteCustomTrackingDomainRequestBuilder(hostname, scope, xApiKey, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteCustomTrackingDomain", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteCustomTrackingDomainRequestBuilder(@javax.annotation.Nonnull String hostname, @javax.annotation.Nonnull String scope, @javax.annotation.Nonnull String xApiKey, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'hostname' is set
    if (hostname == null) {
      throw new ApiException(400, "Missing the required parameter 'hostname' when calling deleteCustomTrackingDomain");
    }
    // verify the required parameter 'scope' is set
    if (scope == null) {
      throw new ApiException(400, "Missing the required parameter 'scope' when calling deleteCustomTrackingDomain");
    }
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling deleteCustomTrackingDomain");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/custom-tracking-domains/{hostname}/{scope}"
        .replace("{hostname}", ApiClient.urlEncode(hostname.toString()))
        .replace("{scope}", ApiClient.urlEncode(scope.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Retrieve Custom Tracking Domains
   * Retrieve all custom tracking domains registered under your account. Optional filters include domain name, status, scope, limit and offset. 
   * @param xApiKey  (required)
   * @param name Filter by custom tracking domain label (optional)
   * @param status Filter by status (optional)
   * @param scope Filter by scope (optional)
   * @param limit The maximum number of domains to return. The default is 100. (optional, default to 100)
   * @param offset The number of domains to skip before returning results. The default is 0. (optional, default to 0)
   * @return CustomTrackingDomainListResponse
   * @throws ApiException if fails to make API call
   */
  public CustomTrackingDomainListResponse listCustomTrackingDomains(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String name, @javax.annotation.Nullable String status, @javax.annotation.Nullable String scope, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset) throws ApiException {
    return listCustomTrackingDomains(xApiKey, name, status, scope, limit, offset, null);
  }

  /**
   * Retrieve Custom Tracking Domains
   * Retrieve all custom tracking domains registered under your account. Optional filters include domain name, status, scope, limit and offset. 
   * @param xApiKey  (required)
   * @param name Filter by custom tracking domain label (optional)
   * @param status Filter by status (optional)
   * @param scope Filter by scope (optional)
   * @param limit The maximum number of domains to return. The default is 100. (optional, default to 100)
   * @param offset The number of domains to skip before returning results. The default is 0. (optional, default to 0)
   * @param headers Optional headers to include in the request
   * @return CustomTrackingDomainListResponse
   * @throws ApiException if fails to make API call
   */
  public CustomTrackingDomainListResponse listCustomTrackingDomains(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String name, @javax.annotation.Nullable String status, @javax.annotation.Nullable String scope, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, Map<String, String> headers) throws ApiException {
    ApiResponse<CustomTrackingDomainListResponse> localVarResponse = listCustomTrackingDomainsWithHttpInfo(xApiKey, name, status, scope, limit, offset, headers);
    return localVarResponse.getData();
  }

  /**
   * Retrieve Custom Tracking Domains
   * Retrieve all custom tracking domains registered under your account. Optional filters include domain name, status, scope, limit and offset. 
   * @param xApiKey  (required)
   * @param name Filter by custom tracking domain label (optional)
   * @param status Filter by status (optional)
   * @param scope Filter by scope (optional)
   * @param limit The maximum number of domains to return. The default is 100. (optional, default to 100)
   * @param offset The number of domains to skip before returning results. The default is 0. (optional, default to 0)
   * @return ApiResponse&lt;CustomTrackingDomainListResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CustomTrackingDomainListResponse> listCustomTrackingDomainsWithHttpInfo(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String name, @javax.annotation.Nullable String status, @javax.annotation.Nullable String scope, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset) throws ApiException {
    return listCustomTrackingDomainsWithHttpInfo(xApiKey, name, status, scope, limit, offset, null);
  }

  /**
   * Retrieve Custom Tracking Domains
   * Retrieve all custom tracking domains registered under your account. Optional filters include domain name, status, scope, limit and offset. 
   * @param xApiKey  (required)
   * @param name Filter by custom tracking domain label (optional)
   * @param status Filter by status (optional)
   * @param scope Filter by scope (optional)
   * @param limit The maximum number of domains to return. The default is 100. (optional, default to 100)
   * @param offset The number of domains to skip before returning results. The default is 0. (optional, default to 0)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CustomTrackingDomainListResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CustomTrackingDomainListResponse> listCustomTrackingDomainsWithHttpInfo(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String name, @javax.annotation.Nullable String status, @javax.annotation.Nullable String scope, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listCustomTrackingDomainsRequestBuilder(xApiKey, name, status, scope, limit, offset, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listCustomTrackingDomains", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CustomTrackingDomainListResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8);
        CustomTrackingDomainListResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CustomTrackingDomainListResponse>() {});
        

        return new ApiResponse<CustomTrackingDomainListResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listCustomTrackingDomainsRequestBuilder(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String name, @javax.annotation.Nullable String status, @javax.annotation.Nullable String scope, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling listCustomTrackingDomains");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/custom-tracking-domains";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "name";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("name", name));
    localVarQueryParameterBaseName = "status";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("status", status));
    localVarQueryParameterBaseName = "scope";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("scope", scope));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "offset";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("offset", offset));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update Custom Tracking Domain
   * Update an existing custom tracking domain by its hostname and scope. Supports updating the custom tracking domain&#39;s name or toggling its active status. 
   * @param hostname  (required)
   * @param scope  (required)
   * @param xApiKey  (required)
   * @param patchCustomTrackingDomainRequest  (required)
   * @return UpdateTrackingResult
   * @throws ApiException if fails to make API call
   */
  public UpdateTrackingResult updateCustomTrackingDomain(@javax.annotation.Nonnull String hostname, @javax.annotation.Nonnull String scope, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull PatchCustomTrackingDomainRequest patchCustomTrackingDomainRequest) throws ApiException {
    return updateCustomTrackingDomain(hostname, scope, xApiKey, patchCustomTrackingDomainRequest, null);
  }

  /**
   * Update Custom Tracking Domain
   * Update an existing custom tracking domain by its hostname and scope. Supports updating the custom tracking domain&#39;s name or toggling its active status. 
   * @param hostname  (required)
   * @param scope  (required)
   * @param xApiKey  (required)
   * @param patchCustomTrackingDomainRequest  (required)
   * @param headers Optional headers to include in the request
   * @return UpdateTrackingResult
   * @throws ApiException if fails to make API call
   */
  public UpdateTrackingResult updateCustomTrackingDomain(@javax.annotation.Nonnull String hostname, @javax.annotation.Nonnull String scope, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull PatchCustomTrackingDomainRequest patchCustomTrackingDomainRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<UpdateTrackingResult> localVarResponse = updateCustomTrackingDomainWithHttpInfo(hostname, scope, xApiKey, patchCustomTrackingDomainRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Update Custom Tracking Domain
   * Update an existing custom tracking domain by its hostname and scope. Supports updating the custom tracking domain&#39;s name or toggling its active status. 
   * @param hostname  (required)
   * @param scope  (required)
   * @param xApiKey  (required)
   * @param patchCustomTrackingDomainRequest  (required)
   * @return ApiResponse&lt;UpdateTrackingResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UpdateTrackingResult> updateCustomTrackingDomainWithHttpInfo(@javax.annotation.Nonnull String hostname, @javax.annotation.Nonnull String scope, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull PatchCustomTrackingDomainRequest patchCustomTrackingDomainRequest) throws ApiException {
    return updateCustomTrackingDomainWithHttpInfo(hostname, scope, xApiKey, patchCustomTrackingDomainRequest, null);
  }

  /**
   * Update Custom Tracking Domain
   * Update an existing custom tracking domain by its hostname and scope. Supports updating the custom tracking domain&#39;s name or toggling its active status. 
   * @param hostname  (required)
   * @param scope  (required)
   * @param xApiKey  (required)
   * @param patchCustomTrackingDomainRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;UpdateTrackingResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UpdateTrackingResult> updateCustomTrackingDomainWithHttpInfo(@javax.annotation.Nonnull String hostname, @javax.annotation.Nonnull String scope, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull PatchCustomTrackingDomainRequest patchCustomTrackingDomainRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateCustomTrackingDomainRequestBuilder(hostname, scope, xApiKey, patchCustomTrackingDomainRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateCustomTrackingDomain", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<UpdateTrackingResult>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8);
        UpdateTrackingResult responseValue = UpdateTrackingResult.decode(localVarResponse.statusCode(), responseBody, memberVarObjectMapper);
        

        return new ApiResponse<UpdateTrackingResult>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateCustomTrackingDomainRequestBuilder(@javax.annotation.Nonnull String hostname, @javax.annotation.Nonnull String scope, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull PatchCustomTrackingDomainRequest patchCustomTrackingDomainRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'hostname' is set
    if (hostname == null) {
      throw new ApiException(400, "Missing the required parameter 'hostname' when calling updateCustomTrackingDomain");
    }
    // verify the required parameter 'scope' is set
    if (scope == null) {
      throw new ApiException(400, "Missing the required parameter 'scope' when calling updateCustomTrackingDomain");
    }
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling updateCustomTrackingDomain");
    }
    // verify the required parameter 'patchCustomTrackingDomainRequest' is set
    if (patchCustomTrackingDomainRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'patchCustomTrackingDomainRequest' when calling updateCustomTrackingDomain");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/custom-tracking-domains/{hostname}/{scope}"
        .replace("{hostname}", ApiClient.urlEncode(hostname.toString()))
        .replace("{scope}", ApiClient.urlEncode(scope.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(patchCustomTrackingDomainRequest);
      localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
