/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.mailchannels.api;

import com.mailchannels.client.ApiClient;
import com.mailchannels.client.ApiException;
import com.mailchannels.client.ApiResponse;
import com.mailchannels.client.Configuration;
import com.mailchannels.client.Pair;

import com.mailchannels.model.CheckDomainBody;
import com.mailchannels.model.CheckDomainResult;
import com.mailchannels.model.DKIMKeyInfo;
import com.mailchannels.model.DKIMKeyList;
import com.mailchannels.model.DKIMKeyPairCreateRequest;
import com.mailchannels.model.DKIMKeyPairUpdateRequest;
import com.mailchannels.model.DKIMKeyRotateRequest;
import com.mailchannels.model.DKIMKeyRotateResponse;
import com.mailchannels.model.ErrorResponse;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class DkimApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public DkimApi() {
    this(Configuration.getDefaultApiClient());
  }

  public DkimApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * DKIM, SPF &amp; Domain Lockdown Check
   * Validates a domain&#39;s email authentication setup by retrieving its DKIM, SPF, and Domain Lockdown status. This endpoint checks whether the domain is properly configured for secure email delivery. 
   * @param xApiKey  (required)
   * @param checkDomainBody  (required)
   * @return CheckDomainResult
   * @throws ApiException if fails to make API call
   */
  public CheckDomainResult checkDomain(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull CheckDomainBody checkDomainBody) throws ApiException {
    return checkDomain(xApiKey, checkDomainBody, null);
  }

  /**
   * DKIM, SPF &amp; Domain Lockdown Check
   * Validates a domain&#39;s email authentication setup by retrieving its DKIM, SPF, and Domain Lockdown status. This endpoint checks whether the domain is properly configured for secure email delivery. 
   * @param xApiKey  (required)
   * @param checkDomainBody  (required)
   * @param headers Optional headers to include in the request
   * @return CheckDomainResult
   * @throws ApiException if fails to make API call
   */
  public CheckDomainResult checkDomain(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull CheckDomainBody checkDomainBody, Map<String, String> headers) throws ApiException {
    ApiResponse<CheckDomainResult> localVarResponse = checkDomainWithHttpInfo(xApiKey, checkDomainBody, headers);
    return localVarResponse.getData();
  }

  /**
   * DKIM, SPF &amp; Domain Lockdown Check
   * Validates a domain&#39;s email authentication setup by retrieving its DKIM, SPF, and Domain Lockdown status. This endpoint checks whether the domain is properly configured for secure email delivery. 
   * @param xApiKey  (required)
   * @param checkDomainBody  (required)
   * @return ApiResponse&lt;CheckDomainResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CheckDomainResult> checkDomainWithHttpInfo(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull CheckDomainBody checkDomainBody) throws ApiException {
    return checkDomainWithHttpInfo(xApiKey, checkDomainBody, null);
  }

  /**
   * DKIM, SPF &amp; Domain Lockdown Check
   * Validates a domain&#39;s email authentication setup by retrieving its DKIM, SPF, and Domain Lockdown status. This endpoint checks whether the domain is properly configured for secure email delivery. 
   * @param xApiKey  (required)
   * @param checkDomainBody  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CheckDomainResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CheckDomainResult> checkDomainWithHttpInfo(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull CheckDomainBody checkDomainBody, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = checkDomainRequestBuilder(xApiKey, checkDomainBody, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("checkDomain", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CheckDomainResult>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CheckDomainResult responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CheckDomainResult>() {});
        

        return new ApiResponse<CheckDomainResult>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder checkDomainRequestBuilder(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull CheckDomainBody checkDomainBody, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling checkDomain");
    }
    // verify the required parameter 'checkDomainBody' is set
    if (checkDomainBody == null) {
      throw new ApiException(400, "Missing the required parameter 'checkDomainBody' when calling checkDomain");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/check-domain";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(checkDomainBody);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Create DKIM Key Pair
   * Create a DKIM key pair for a specified domain and selector using the specified algorithm and key length, for the current customer. 
   * @param domain  (required)
   * @param xApiKey  (required)
   * @param dkIMKeyPairCreateRequest  (required)
   * @return DKIMKeyInfo
   * @throws ApiException if fails to make API call
   */
  public DKIMKeyInfo createDkimKey(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull DKIMKeyPairCreateRequest dkIMKeyPairCreateRequest) throws ApiException {
    return createDkimKey(domain, xApiKey, dkIMKeyPairCreateRequest, null);
  }

  /**
   * Create DKIM Key Pair
   * Create a DKIM key pair for a specified domain and selector using the specified algorithm and key length, for the current customer. 
   * @param domain  (required)
   * @param xApiKey  (required)
   * @param dkIMKeyPairCreateRequest  (required)
   * @param headers Optional headers to include in the request
   * @return DKIMKeyInfo
   * @throws ApiException if fails to make API call
   */
  public DKIMKeyInfo createDkimKey(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull DKIMKeyPairCreateRequest dkIMKeyPairCreateRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<DKIMKeyInfo> localVarResponse = createDkimKeyWithHttpInfo(domain, xApiKey, dkIMKeyPairCreateRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Create DKIM Key Pair
   * Create a DKIM key pair for a specified domain and selector using the specified algorithm and key length, for the current customer. 
   * @param domain  (required)
   * @param xApiKey  (required)
   * @param dkIMKeyPairCreateRequest  (required)
   * @return ApiResponse&lt;DKIMKeyInfo&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DKIMKeyInfo> createDkimKeyWithHttpInfo(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull DKIMKeyPairCreateRequest dkIMKeyPairCreateRequest) throws ApiException {
    return createDkimKeyWithHttpInfo(domain, xApiKey, dkIMKeyPairCreateRequest, null);
  }

  /**
   * Create DKIM Key Pair
   * Create a DKIM key pair for a specified domain and selector using the specified algorithm and key length, for the current customer. 
   * @param domain  (required)
   * @param xApiKey  (required)
   * @param dkIMKeyPairCreateRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DKIMKeyInfo&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DKIMKeyInfo> createDkimKeyWithHttpInfo(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull DKIMKeyPairCreateRequest dkIMKeyPairCreateRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createDkimKeyRequestBuilder(domain, xApiKey, dkIMKeyPairCreateRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createDkimKey", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DKIMKeyInfo>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DKIMKeyInfo responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DKIMKeyInfo>() {});
        

        return new ApiResponse<DKIMKeyInfo>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createDkimKeyRequestBuilder(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull DKIMKeyPairCreateRequest dkIMKeyPairCreateRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'domain' is set
    if (domain == null) {
      throw new ApiException(400, "Missing the required parameter 'domain' when calling createDkimKey");
    }
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling createDkimKey");
    }
    // verify the required parameter 'dkIMKeyPairCreateRequest' is set
    if (dkIMKeyPairCreateRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'dkIMKeyPairCreateRequest' when calling createDkimKey");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/domains/{domain}/dkim-keys"
        .replace("{domain}", ApiClient.urlEncode(domain.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(dkIMKeyPairCreateRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Retrieve DKIM Keys
   * Search for DKIM keys by domain, with optional filters. If selector is provided, at most one key will be returned. 
   * @param domain  (required)
   * @param xApiKey  (required)
   * @param selector  (optional)
   * @param status  (optional)
   * @param offset Number of keys to skip before returning results. The default is 0.  (optional, default to 0)
   * @param limit Maximum number of keys to return. The default is 10.  (optional, default to 10)
   * @param includeDnsRecord If true, includes the suggested DKIM DNS record for each returned key. Defaults to false.  (optional, default to false)
   * @return DKIMKeyList
   * @throws ApiException if fails to make API call
   */
  public DKIMKeyList listDkimKeys(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String selector, @javax.annotation.Nullable String status, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Boolean includeDnsRecord) throws ApiException {
    return listDkimKeys(domain, xApiKey, selector, status, offset, limit, includeDnsRecord, null);
  }

  /**
   * Retrieve DKIM Keys
   * Search for DKIM keys by domain, with optional filters. If selector is provided, at most one key will be returned. 
   * @param domain  (required)
   * @param xApiKey  (required)
   * @param selector  (optional)
   * @param status  (optional)
   * @param offset Number of keys to skip before returning results. The default is 0.  (optional, default to 0)
   * @param limit Maximum number of keys to return. The default is 10.  (optional, default to 10)
   * @param includeDnsRecord If true, includes the suggested DKIM DNS record for each returned key. Defaults to false.  (optional, default to false)
   * @param headers Optional headers to include in the request
   * @return DKIMKeyList
   * @throws ApiException if fails to make API call
   */
  public DKIMKeyList listDkimKeys(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String selector, @javax.annotation.Nullable String status, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Boolean includeDnsRecord, Map<String, String> headers) throws ApiException {
    ApiResponse<DKIMKeyList> localVarResponse = listDkimKeysWithHttpInfo(domain, xApiKey, selector, status, offset, limit, includeDnsRecord, headers);
    return localVarResponse.getData();
  }

  /**
   * Retrieve DKIM Keys
   * Search for DKIM keys by domain, with optional filters. If selector is provided, at most one key will be returned. 
   * @param domain  (required)
   * @param xApiKey  (required)
   * @param selector  (optional)
   * @param status  (optional)
   * @param offset Number of keys to skip before returning results. The default is 0.  (optional, default to 0)
   * @param limit Maximum number of keys to return. The default is 10.  (optional, default to 10)
   * @param includeDnsRecord If true, includes the suggested DKIM DNS record for each returned key. Defaults to false.  (optional, default to false)
   * @return ApiResponse&lt;DKIMKeyList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DKIMKeyList> listDkimKeysWithHttpInfo(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String selector, @javax.annotation.Nullable String status, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Boolean includeDnsRecord) throws ApiException {
    return listDkimKeysWithHttpInfo(domain, xApiKey, selector, status, offset, limit, includeDnsRecord, null);
  }

  /**
   * Retrieve DKIM Keys
   * Search for DKIM keys by domain, with optional filters. If selector is provided, at most one key will be returned. 
   * @param domain  (required)
   * @param xApiKey  (required)
   * @param selector  (optional)
   * @param status  (optional)
   * @param offset Number of keys to skip before returning results. The default is 0.  (optional, default to 0)
   * @param limit Maximum number of keys to return. The default is 10.  (optional, default to 10)
   * @param includeDnsRecord If true, includes the suggested DKIM DNS record for each returned key. Defaults to false.  (optional, default to false)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DKIMKeyList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DKIMKeyList> listDkimKeysWithHttpInfo(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String selector, @javax.annotation.Nullable String status, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Boolean includeDnsRecord, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listDkimKeysRequestBuilder(domain, xApiKey, selector, status, offset, limit, includeDnsRecord, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listDkimKeys", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DKIMKeyList>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DKIMKeyList responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DKIMKeyList>() {});
        

        return new ApiResponse<DKIMKeyList>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listDkimKeysRequestBuilder(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String selector, @javax.annotation.Nullable String status, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Boolean includeDnsRecord, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'domain' is set
    if (domain == null) {
      throw new ApiException(400, "Missing the required parameter 'domain' when calling listDkimKeys");
    }
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling listDkimKeys");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/domains/{domain}/dkim-keys"
        .replace("{domain}", ApiClient.urlEncode(domain.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "selector";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("selector", selector));
    localVarQueryParameterBaseName = "status";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("status", status));
    localVarQueryParameterBaseName = "offset";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("offset", offset));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "include_dns_record";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("include_dns_record", includeDnsRecord));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Rotate DKIM Key Pair
   * Rotate an active DKIM key pair. Mark the original key as &#39;rotated&#39;, and create a new key pair with the required new key selector, reusing the same algorithm and key length. The rotated key remains valid for signing for a 3-day grace period, and is automatically changed to &#39;retired&#39; 2 weeks after rotation. Publish the new key to its DNS TXT record before rotated key expires for signing as emails sent with an unpublished key will fail DKIM validation by receiving providers. After the grace period, only the new key is valid for signing if published.
   * @param domain  (required)
   * @param selector  (required)
   * @param xApiKey  (required)
   * @param dkIMKeyRotateRequest  (required)
   * @return DKIMKeyRotateResponse
   * @throws ApiException if fails to make API call
   */
  public DKIMKeyRotateResponse rotateDkimKey(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String selector, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull DKIMKeyRotateRequest dkIMKeyRotateRequest) throws ApiException {
    return rotateDkimKey(domain, selector, xApiKey, dkIMKeyRotateRequest, null);
  }

  /**
   * Rotate DKIM Key Pair
   * Rotate an active DKIM key pair. Mark the original key as &#39;rotated&#39;, and create a new key pair with the required new key selector, reusing the same algorithm and key length. The rotated key remains valid for signing for a 3-day grace period, and is automatically changed to &#39;retired&#39; 2 weeks after rotation. Publish the new key to its DNS TXT record before rotated key expires for signing as emails sent with an unpublished key will fail DKIM validation by receiving providers. After the grace period, only the new key is valid for signing if published.
   * @param domain  (required)
   * @param selector  (required)
   * @param xApiKey  (required)
   * @param dkIMKeyRotateRequest  (required)
   * @param headers Optional headers to include in the request
   * @return DKIMKeyRotateResponse
   * @throws ApiException if fails to make API call
   */
  public DKIMKeyRotateResponse rotateDkimKey(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String selector, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull DKIMKeyRotateRequest dkIMKeyRotateRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<DKIMKeyRotateResponse> localVarResponse = rotateDkimKeyWithHttpInfo(domain, selector, xApiKey, dkIMKeyRotateRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Rotate DKIM Key Pair
   * Rotate an active DKIM key pair. Mark the original key as &#39;rotated&#39;, and create a new key pair with the required new key selector, reusing the same algorithm and key length. The rotated key remains valid for signing for a 3-day grace period, and is automatically changed to &#39;retired&#39; 2 weeks after rotation. Publish the new key to its DNS TXT record before rotated key expires for signing as emails sent with an unpublished key will fail DKIM validation by receiving providers. After the grace period, only the new key is valid for signing if published.
   * @param domain  (required)
   * @param selector  (required)
   * @param xApiKey  (required)
   * @param dkIMKeyRotateRequest  (required)
   * @return ApiResponse&lt;DKIMKeyRotateResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DKIMKeyRotateResponse> rotateDkimKeyWithHttpInfo(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String selector, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull DKIMKeyRotateRequest dkIMKeyRotateRequest) throws ApiException {
    return rotateDkimKeyWithHttpInfo(domain, selector, xApiKey, dkIMKeyRotateRequest, null);
  }

  /**
   * Rotate DKIM Key Pair
   * Rotate an active DKIM key pair. Mark the original key as &#39;rotated&#39;, and create a new key pair with the required new key selector, reusing the same algorithm and key length. The rotated key remains valid for signing for a 3-day grace period, and is automatically changed to &#39;retired&#39; 2 weeks after rotation. Publish the new key to its DNS TXT record before rotated key expires for signing as emails sent with an unpublished key will fail DKIM validation by receiving providers. After the grace period, only the new key is valid for signing if published.
   * @param domain  (required)
   * @param selector  (required)
   * @param xApiKey  (required)
   * @param dkIMKeyRotateRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DKIMKeyRotateResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DKIMKeyRotateResponse> rotateDkimKeyWithHttpInfo(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String selector, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull DKIMKeyRotateRequest dkIMKeyRotateRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = rotateDkimKeyRequestBuilder(domain, selector, xApiKey, dkIMKeyRotateRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("rotateDkimKey", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DKIMKeyRotateResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DKIMKeyRotateResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DKIMKeyRotateResponse>() {});
        

        return new ApiResponse<DKIMKeyRotateResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder rotateDkimKeyRequestBuilder(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String selector, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull DKIMKeyRotateRequest dkIMKeyRotateRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'domain' is set
    if (domain == null) {
      throw new ApiException(400, "Missing the required parameter 'domain' when calling rotateDkimKey");
    }
    // verify the required parameter 'selector' is set
    if (selector == null) {
      throw new ApiException(400, "Missing the required parameter 'selector' when calling rotateDkimKey");
    }
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling rotateDkimKey");
    }
    // verify the required parameter 'dkIMKeyRotateRequest' is set
    if (dkIMKeyRotateRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'dkIMKeyRotateRequest' when calling rotateDkimKey");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/domains/{domain}/dkim-keys/{selector}/rotate"
        .replace("{domain}", ApiClient.urlEncode(domain.toString()))
        .replace("{selector}", ApiClient.urlEncode(selector.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(dkIMKeyRotateRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update DKIM Key Status
   * Update fields of an existing DKIM key pair for the specified domain and selector, for the current customer. Currently, only the status field can be updated. revoked: Indicates that the key is compromised and should not be used. retired: Indicates that the key has been rotated and is no longer in use. rotated: Indicates that the key is going through the rotation process. Only active key pairs can be updated to this status, and no new key pair is created. The rotated key can be used to sign emails for 3 days after the status update, and will automatically change to &#39;retired&#39; 2 weeks after update. For a smooth key transition, it is recommended to create and publish a new key pair before signing is disabled for the rotated key. 
   * @param domain  (required)
   * @param selector  (required)
   * @param xApiKey  (required)
   * @param dkIMKeyPairUpdateRequest  (required)
   * @throws ApiException if fails to make API call
   */
  public void updateDkimKey(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String selector, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull DKIMKeyPairUpdateRequest dkIMKeyPairUpdateRequest) throws ApiException {
    updateDkimKey(domain, selector, xApiKey, dkIMKeyPairUpdateRequest, null);
  }

  /**
   * Update DKIM Key Status
   * Update fields of an existing DKIM key pair for the specified domain and selector, for the current customer. Currently, only the status field can be updated. revoked: Indicates that the key is compromised and should not be used. retired: Indicates that the key has been rotated and is no longer in use. rotated: Indicates that the key is going through the rotation process. Only active key pairs can be updated to this status, and no new key pair is created. The rotated key can be used to sign emails for 3 days after the status update, and will automatically change to &#39;retired&#39; 2 weeks after update. For a smooth key transition, it is recommended to create and publish a new key pair before signing is disabled for the rotated key. 
   * @param domain  (required)
   * @param selector  (required)
   * @param xApiKey  (required)
   * @param dkIMKeyPairUpdateRequest  (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void updateDkimKey(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String selector, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull DKIMKeyPairUpdateRequest dkIMKeyPairUpdateRequest, Map<String, String> headers) throws ApiException {
    updateDkimKeyWithHttpInfo(domain, selector, xApiKey, dkIMKeyPairUpdateRequest, headers);
  }

  /**
   * Update DKIM Key Status
   * Update fields of an existing DKIM key pair for the specified domain and selector, for the current customer. Currently, only the status field can be updated. revoked: Indicates that the key is compromised and should not be used. retired: Indicates that the key has been rotated and is no longer in use. rotated: Indicates that the key is going through the rotation process. Only active key pairs can be updated to this status, and no new key pair is created. The rotated key can be used to sign emails for 3 days after the status update, and will automatically change to &#39;retired&#39; 2 weeks after update. For a smooth key transition, it is recommended to create and publish a new key pair before signing is disabled for the rotated key. 
   * @param domain  (required)
   * @param selector  (required)
   * @param xApiKey  (required)
   * @param dkIMKeyPairUpdateRequest  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> updateDkimKeyWithHttpInfo(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String selector, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull DKIMKeyPairUpdateRequest dkIMKeyPairUpdateRequest) throws ApiException {
    return updateDkimKeyWithHttpInfo(domain, selector, xApiKey, dkIMKeyPairUpdateRequest, null);
  }

  /**
   * Update DKIM Key Status
   * Update fields of an existing DKIM key pair for the specified domain and selector, for the current customer. Currently, only the status field can be updated. revoked: Indicates that the key is compromised and should not be used. retired: Indicates that the key has been rotated and is no longer in use. rotated: Indicates that the key is going through the rotation process. Only active key pairs can be updated to this status, and no new key pair is created. The rotated key can be used to sign emails for 3 days after the status update, and will automatically change to &#39;retired&#39; 2 weeks after update. For a smooth key transition, it is recommended to create and publish a new key pair before signing is disabled for the rotated key. 
   * @param domain  (required)
   * @param selector  (required)
   * @param xApiKey  (required)
   * @param dkIMKeyPairUpdateRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> updateDkimKeyWithHttpInfo(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String selector, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull DKIMKeyPairUpdateRequest dkIMKeyPairUpdateRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateDkimKeyRequestBuilder(domain, selector, xApiKey, dkIMKeyPairUpdateRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateDkimKey", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateDkimKeyRequestBuilder(@javax.annotation.Nonnull String domain, @javax.annotation.Nonnull String selector, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull DKIMKeyPairUpdateRequest dkIMKeyPairUpdateRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'domain' is set
    if (domain == null) {
      throw new ApiException(400, "Missing the required parameter 'domain' when calling updateDkimKey");
    }
    // verify the required parameter 'selector' is set
    if (selector == null) {
      throw new ApiException(400, "Missing the required parameter 'selector' when calling updateDkimKey");
    }
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling updateDkimKey");
    }
    // verify the required parameter 'dkIMKeyPairUpdateRequest' is set
    if (dkIMKeyPairUpdateRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'dkIMKeyPairUpdateRequest' when calling updateDkimKey");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/domains/{domain}/dkim-keys/{selector}"
        .replace("{domain}", ApiClient.urlEncode(domain.toString()))
        .replace("{selector}", ApiClient.urlEncode(selector.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(dkIMKeyPairUpdateRequest);
      localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
