/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.mailchannels.api;

import com.mailchannels.model.SendEmailResult;
import com.mailchannels.client.ApiClient;
import com.mailchannels.client.ApiException;
import com.mailchannels.client.ApiResponse;
import com.mailchannels.client.Configuration;
import com.mailchannels.client.Pair;

import com.mailchannels.model.AsyncSendResponse;
import com.mailchannels.model.ErrorResponse;
import com.mailchannels.model.MailSendBody;
import com.mailchannels.model.Message;
import com.mailchannels.model.SendResults;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class SendApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public SendApi() {
    this(Configuration.getDefaultApiClient());
  }

  public SendApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Send an Email Asynchronously
   * Queues an email message for asynchronous processing and returns immediately with a request ID.  The email will be processed in the background, and you&#39;ll receive webhook events for all delivery status updates (e.g. dropped, processed, delivered, hard-bounced). These webhook events are identical to those sent for the synchronous /send endpoint.  Use this endpoint when you need to send emails without waiting for processing to complete. This can improve your application&#39;s response time, especially when sending to multiple recipients. 
   * @param xApiKey  (required)
   * @param mailSendBody  (required)
   * @return AsyncSendResponse
   * @throws ApiException if fails to make API call
   */
  public AsyncSendResponse queueEmail(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull MailSendBody mailSendBody) throws ApiException {
    return queueEmail(xApiKey, mailSendBody, null);
  }

  /**
   * Send an Email Asynchronously
   * Queues an email message for asynchronous processing and returns immediately with a request ID.  The email will be processed in the background, and you&#39;ll receive webhook events for all delivery status updates (e.g. dropped, processed, delivered, hard-bounced). These webhook events are identical to those sent for the synchronous /send endpoint.  Use this endpoint when you need to send emails without waiting for processing to complete. This can improve your application&#39;s response time, especially when sending to multiple recipients. 
   * @param xApiKey  (required)
   * @param mailSendBody  (required)
   * @param headers Optional headers to include in the request
   * @return AsyncSendResponse
   * @throws ApiException if fails to make API call
   */
  public AsyncSendResponse queueEmail(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull MailSendBody mailSendBody, Map<String, String> headers) throws ApiException {
    ApiResponse<AsyncSendResponse> localVarResponse = queueEmailWithHttpInfo(xApiKey, mailSendBody, headers);
    return localVarResponse.getData();
  }

  /**
   * Send an Email Asynchronously
   * Queues an email message for asynchronous processing and returns immediately with a request ID.  The email will be processed in the background, and you&#39;ll receive webhook events for all delivery status updates (e.g. dropped, processed, delivered, hard-bounced). These webhook events are identical to those sent for the synchronous /send endpoint.  Use this endpoint when you need to send emails without waiting for processing to complete. This can improve your application&#39;s response time, especially when sending to multiple recipients. 
   * @param xApiKey  (required)
   * @param mailSendBody  (required)
   * @return ApiResponse&lt;AsyncSendResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<AsyncSendResponse> queueEmailWithHttpInfo(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull MailSendBody mailSendBody) throws ApiException {
    return queueEmailWithHttpInfo(xApiKey, mailSendBody, null);
  }

  /**
   * Send an Email Asynchronously
   * Queues an email message for asynchronous processing and returns immediately with a request ID.  The email will be processed in the background, and you&#39;ll receive webhook events for all delivery status updates (e.g. dropped, processed, delivered, hard-bounced). These webhook events are identical to those sent for the synchronous /send endpoint.  Use this endpoint when you need to send emails without waiting for processing to complete. This can improve your application&#39;s response time, especially when sending to multiple recipients. 
   * @param xApiKey  (required)
   * @param mailSendBody  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;AsyncSendResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<AsyncSendResponse> queueEmailWithHttpInfo(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull MailSendBody mailSendBody, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = queueEmailRequestBuilder(xApiKey, mailSendBody, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("queueEmail", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<AsyncSendResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8);
        AsyncSendResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<AsyncSendResponse>() {});
        

        return new ApiResponse<AsyncSendResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder queueEmailRequestBuilder(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull MailSendBody mailSendBody, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling queueEmail");
    }
    // verify the required parameter 'mailSendBody' is set
    if (mailSendBody == null) {
      throw new ApiException(400, "Missing the required parameter 'mailSendBody' when calling queueEmail");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/send-async";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(mailSendBody);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Send an Email
   * Sends an email message to one or more recipients.  **Click Tracking Notes:** Only links (&#x60;&lt;a&gt;&#x60; tags) meeting all of the following conditions are processed for click tracking: - The URL is non-empty. - The URL starts with \&quot;http\&quot; or \&quot;https\&quot;. - The link does not have a clicktracking attribute set to &#39;off&#39;. 
   * @param xApiKey  (required)
   * @param mailSendBody  (required)
   * @param dryRun When present and set to true, the message will not be sent. Instead, the fully rendered message is returned. This can be useful for testing.  (optional)
   * @return SendEmailResult
   * @throws ApiException if fails to make API call
   */
  public SendEmailResult sendEmail(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull MailSendBody mailSendBody, @javax.annotation.Nullable Boolean dryRun) throws ApiException {
    return sendEmail(xApiKey, mailSendBody, dryRun, null);
  }

  /**
   * Send an Email
   * Sends an email message to one or more recipients.  **Click Tracking Notes:** Only links (&#x60;&lt;a&gt;&#x60; tags) meeting all of the following conditions are processed for click tracking: - The URL is non-empty. - The URL starts with \&quot;http\&quot; or \&quot;https\&quot;. - The link does not have a clicktracking attribute set to &#39;off&#39;. 
   * @param xApiKey  (required)
   * @param mailSendBody  (required)
   * @param dryRun When present and set to true, the message will not be sent. Instead, the fully rendered message is returned. This can be useful for testing.  (optional)
   * @param headers Optional headers to include in the request
   * @return SendEmailResult
   * @throws ApiException if fails to make API call
   */
  public SendEmailResult sendEmail(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull MailSendBody mailSendBody, @javax.annotation.Nullable Boolean dryRun, Map<String, String> headers) throws ApiException {
    ApiResponse<SendEmailResult> localVarResponse = sendEmailWithHttpInfo(xApiKey, mailSendBody, dryRun, headers);
    return localVarResponse.getData();
  }

  /**
   * Send an Email
   * Sends an email message to one or more recipients.  **Click Tracking Notes:** Only links (&#x60;&lt;a&gt;&#x60; tags) meeting all of the following conditions are processed for click tracking: - The URL is non-empty. - The URL starts with \&quot;http\&quot; or \&quot;https\&quot;. - The link does not have a clicktracking attribute set to &#39;off&#39;. 
   * @param xApiKey  (required)
   * @param mailSendBody  (required)
   * @param dryRun When present and set to true, the message will not be sent. Instead, the fully rendered message is returned. This can be useful for testing.  (optional)
   * @return ApiResponse&lt;SendEmailResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SendEmailResult> sendEmailWithHttpInfo(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull MailSendBody mailSendBody, @javax.annotation.Nullable Boolean dryRun) throws ApiException {
    return sendEmailWithHttpInfo(xApiKey, mailSendBody, dryRun, null);
  }

  /**
   * Send an Email
   * Sends an email message to one or more recipients.  **Click Tracking Notes:** Only links (&#x60;&lt;a&gt;&#x60; tags) meeting all of the following conditions are processed for click tracking: - The URL is non-empty. - The URL starts with \&quot;http\&quot; or \&quot;https\&quot;. - The link does not have a clicktracking attribute set to &#39;off&#39;. 
   * @param xApiKey  (required)
   * @param mailSendBody  (required)
   * @param dryRun When present and set to true, the message will not be sent. Instead, the fully rendered message is returned. This can be useful for testing.  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;SendEmailResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SendEmailResult> sendEmailWithHttpInfo(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull MailSendBody mailSendBody, @javax.annotation.Nullable Boolean dryRun, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = sendEmailRequestBuilder(xApiKey, mailSendBody, dryRun, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("sendEmail", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<SendEmailResult>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8);
        SendEmailResult responseValue = SendEmailResult.decode(localVarResponse.statusCode(), responseBody, memberVarObjectMapper);
        

        return new ApiResponse<SendEmailResult>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder sendEmailRequestBuilder(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull MailSendBody mailSendBody, @javax.annotation.Nullable Boolean dryRun, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling sendEmail");
    }
    // verify the required parameter 'mailSendBody' is set
    if (mailSendBody == null) {
      throw new ApiException(400, "Missing the required parameter 'mailSendBody' when calling sendEmail");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/send";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "dry-run";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("dry-run", dryRun));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(mailSendBody);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
