/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.mailchannels.api;

import com.mailchannels.client.ApiClient;
import com.mailchannels.client.ApiException;
import com.mailchannels.client.ApiResponse;
import com.mailchannels.client.Configuration;
import com.mailchannels.client.Pair;

import com.mailchannels.model.ErrorResponse;
import com.mailchannels.model.SuppressionListInput;
import com.mailchannels.model.SuppressionListResponse;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class SuppressionApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public SuppressionApi() {
    this(Configuration.getDefaultApiClient());
  }

  public SuppressionApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Create Suppression Entries
   * Creates suppression entries for the specified account. Parent accounts can create suppression entries for all associated sub-accounts. If suppression_type is not provided, it defaults to &#39;non-transactional&#39;. The operation is atomic, meaning all entries are successfully added or none are added if an error occurs. 
   * @param xApiKey  (required)
   * @param suppressionListInput The details of the suppression entries to create. (required)
   * @throws ApiException if fails to make API call
   */
  public void createSuppressions(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull SuppressionListInput suppressionListInput) throws ApiException {
    createSuppressions(xApiKey, suppressionListInput, null);
  }

  /**
   * Create Suppression Entries
   * Creates suppression entries for the specified account. Parent accounts can create suppression entries for all associated sub-accounts. If suppression_type is not provided, it defaults to &#39;non-transactional&#39;. The operation is atomic, meaning all entries are successfully added or none are added if an error occurs. 
   * @param xApiKey  (required)
   * @param suppressionListInput The details of the suppression entries to create. (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void createSuppressions(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull SuppressionListInput suppressionListInput, Map<String, String> headers) throws ApiException {
    createSuppressionsWithHttpInfo(xApiKey, suppressionListInput, headers);
  }

  /**
   * Create Suppression Entries
   * Creates suppression entries for the specified account. Parent accounts can create suppression entries for all associated sub-accounts. If suppression_type is not provided, it defaults to &#39;non-transactional&#39;. The operation is atomic, meaning all entries are successfully added or none are added if an error occurs. 
   * @param xApiKey  (required)
   * @param suppressionListInput The details of the suppression entries to create. (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> createSuppressionsWithHttpInfo(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull SuppressionListInput suppressionListInput) throws ApiException {
    return createSuppressionsWithHttpInfo(xApiKey, suppressionListInput, null);
  }

  /**
   * Create Suppression Entries
   * Creates suppression entries for the specified account. Parent accounts can create suppression entries for all associated sub-accounts. If suppression_type is not provided, it defaults to &#39;non-transactional&#39;. The operation is atomic, meaning all entries are successfully added or none are added if an error occurs. 
   * @param xApiKey  (required)
   * @param suppressionListInput The details of the suppression entries to create. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> createSuppressionsWithHttpInfo(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull SuppressionListInput suppressionListInput, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createSuppressionsRequestBuilder(xApiKey, suppressionListInput, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createSuppressions", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createSuppressionsRequestBuilder(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nonnull SuppressionListInput suppressionListInput, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling createSuppressions");
    }
    // verify the required parameter 'suppressionListInput' is set
    if (suppressionListInput == null) {
      throw new ApiException(400, "Missing the required parameter 'suppressionListInput' when calling createSuppressions");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/suppression-list";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(suppressionListInput);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete Suppression Entry
   * Deletes suppression entry associated with the account based on the specified recipient and source. If source is not provided, it defaults to &#39;api&#39;. If source is set to &#39;all&#39;, all suppression entries related to the specified recipient will be deleted. 
   * @param recipient  (required)
   * @param xApiKey  (required)
   * @param source  (optional, default to api)
   * @throws ApiException if fails to make API call
   */
  public void deleteSuppression(@javax.annotation.Nonnull String recipient, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String source) throws ApiException {
    deleteSuppression(recipient, xApiKey, source, null);
  }

  /**
   * Delete Suppression Entry
   * Deletes suppression entry associated with the account based on the specified recipient and source. If source is not provided, it defaults to &#39;api&#39;. If source is set to &#39;all&#39;, all suppression entries related to the specified recipient will be deleted. 
   * @param recipient  (required)
   * @param xApiKey  (required)
   * @param source  (optional, default to api)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void deleteSuppression(@javax.annotation.Nonnull String recipient, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String source, Map<String, String> headers) throws ApiException {
    deleteSuppressionWithHttpInfo(recipient, xApiKey, source, headers);
  }

  /**
   * Delete Suppression Entry
   * Deletes suppression entry associated with the account based on the specified recipient and source. If source is not provided, it defaults to &#39;api&#39;. If source is set to &#39;all&#39;, all suppression entries related to the specified recipient will be deleted. 
   * @param recipient  (required)
   * @param xApiKey  (required)
   * @param source  (optional, default to api)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteSuppressionWithHttpInfo(@javax.annotation.Nonnull String recipient, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String source) throws ApiException {
    return deleteSuppressionWithHttpInfo(recipient, xApiKey, source, null);
  }

  /**
   * Delete Suppression Entry
   * Deletes suppression entry associated with the account based on the specified recipient and source. If source is not provided, it defaults to &#39;api&#39;. If source is set to &#39;all&#39;, all suppression entries related to the specified recipient will be deleted. 
   * @param recipient  (required)
   * @param xApiKey  (required)
   * @param source  (optional, default to api)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteSuppressionWithHttpInfo(@javax.annotation.Nonnull String recipient, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String source, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteSuppressionRequestBuilder(recipient, xApiKey, source, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteSuppression", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteSuppressionRequestBuilder(@javax.annotation.Nonnull String recipient, @javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String source, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'recipient' is set
    if (recipient == null) {
      throw new ApiException(400, "Missing the required parameter 'recipient' when calling deleteSuppression");
    }
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling deleteSuppression");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/suppression-list/recipients/{recipient}"
        .replace("{recipient}", ApiClient.urlEncode(recipient.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "source";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("source", source));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Retrieve Suppression List
   * Retrieve suppression entries associated with the specified account. Supports filtering by recipient, source and creation date range. The response is paginated, with a default limit of 1000 entries per page and an offset of 0. 
   * @param xApiKey  (required)
   * @param recipient  (optional)
   * @param source  (optional)
   * @param createdBefore The date and/or time before which the suppression entries were created. Format: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ  (optional)
   * @param createdAfter The date and/or time after which the suppression entries were created. Format: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ  (optional)
   * @param limit The maximum number of suppression entries to return. The default is 1000.  (optional, default to 1000)
   * @param offset The number of suppression entries to skip before returning results. The default is 0.  (optional, default to 0)
   * @return SuppressionListResponse
   * @throws ApiException if fails to make API call
   */
  public SuppressionListResponse listSuppressions(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String recipient, @javax.annotation.Nullable String source, @javax.annotation.Nullable String createdBefore, @javax.annotation.Nullable String createdAfter, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset) throws ApiException {
    return listSuppressions(xApiKey, recipient, source, createdBefore, createdAfter, limit, offset, null);
  }

  /**
   * Retrieve Suppression List
   * Retrieve suppression entries associated with the specified account. Supports filtering by recipient, source and creation date range. The response is paginated, with a default limit of 1000 entries per page and an offset of 0. 
   * @param xApiKey  (required)
   * @param recipient  (optional)
   * @param source  (optional)
   * @param createdBefore The date and/or time before which the suppression entries were created. Format: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ  (optional)
   * @param createdAfter The date and/or time after which the suppression entries were created. Format: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ  (optional)
   * @param limit The maximum number of suppression entries to return. The default is 1000.  (optional, default to 1000)
   * @param offset The number of suppression entries to skip before returning results. The default is 0.  (optional, default to 0)
   * @param headers Optional headers to include in the request
   * @return SuppressionListResponse
   * @throws ApiException if fails to make API call
   */
  public SuppressionListResponse listSuppressions(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String recipient, @javax.annotation.Nullable String source, @javax.annotation.Nullable String createdBefore, @javax.annotation.Nullable String createdAfter, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, Map<String, String> headers) throws ApiException {
    ApiResponse<SuppressionListResponse> localVarResponse = listSuppressionsWithHttpInfo(xApiKey, recipient, source, createdBefore, createdAfter, limit, offset, headers);
    return localVarResponse.getData();
  }

  /**
   * Retrieve Suppression List
   * Retrieve suppression entries associated with the specified account. Supports filtering by recipient, source and creation date range. The response is paginated, with a default limit of 1000 entries per page and an offset of 0. 
   * @param xApiKey  (required)
   * @param recipient  (optional)
   * @param source  (optional)
   * @param createdBefore The date and/or time before which the suppression entries were created. Format: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ  (optional)
   * @param createdAfter The date and/or time after which the suppression entries were created. Format: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ  (optional)
   * @param limit The maximum number of suppression entries to return. The default is 1000.  (optional, default to 1000)
   * @param offset The number of suppression entries to skip before returning results. The default is 0.  (optional, default to 0)
   * @return ApiResponse&lt;SuppressionListResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SuppressionListResponse> listSuppressionsWithHttpInfo(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String recipient, @javax.annotation.Nullable String source, @javax.annotation.Nullable String createdBefore, @javax.annotation.Nullable String createdAfter, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset) throws ApiException {
    return listSuppressionsWithHttpInfo(xApiKey, recipient, source, createdBefore, createdAfter, limit, offset, null);
  }

  /**
   * Retrieve Suppression List
   * Retrieve suppression entries associated with the specified account. Supports filtering by recipient, source and creation date range. The response is paginated, with a default limit of 1000 entries per page and an offset of 0. 
   * @param xApiKey  (required)
   * @param recipient  (optional)
   * @param source  (optional)
   * @param createdBefore The date and/or time before which the suppression entries were created. Format: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ  (optional)
   * @param createdAfter The date and/or time after which the suppression entries were created. Format: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ  (optional)
   * @param limit The maximum number of suppression entries to return. The default is 1000.  (optional, default to 1000)
   * @param offset The number of suppression entries to skip before returning results. The default is 0.  (optional, default to 0)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;SuppressionListResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SuppressionListResponse> listSuppressionsWithHttpInfo(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String recipient, @javax.annotation.Nullable String source, @javax.annotation.Nullable String createdBefore, @javax.annotation.Nullable String createdAfter, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listSuppressionsRequestBuilder(xApiKey, recipient, source, createdBefore, createdAfter, limit, offset, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listSuppressions", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<SuppressionListResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        SuppressionListResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<SuppressionListResponse>() {});
        

        return new ApiResponse<SuppressionListResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listSuppressionsRequestBuilder(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String recipient, @javax.annotation.Nullable String source, @javax.annotation.Nullable String createdBefore, @javax.annotation.Nullable String createdAfter, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling listSuppressions");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/suppression-list";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "recipient";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("recipient", recipient));
    localVarQueryParameterBaseName = "source";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("source", source));
    localVarQueryParameterBaseName = "created_before";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("created_before", createdBefore));
    localVarQueryParameterBaseName = "created_after";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("created_after", createdAfter));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "offset";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("offset", offset));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
