/*
 * Email API
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.mailchannels.api;

import com.mailchannels.client.ApiClient;
import com.mailchannels.client.ApiException;
import com.mailchannels.client.ApiResponse;
import com.mailchannels.client.Configuration;
import com.mailchannels.client.Pair;

import com.mailchannels.model.ErrorResponse;
import com.mailchannels.model.Key;
import com.mailchannels.model.Webhook;
import com.mailchannels.model.WebhookBatchResult;
import com.mailchannels.model.WebhookResendResponse;
import com.mailchannels.model.WebhookValidationRequestBody;
import com.mailchannels.model.WebhookValidationResults;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.26.0")
public class WebhooksApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public WebhooksApi() {
    this(Configuration.getDefaultApiClient());
  }

  public WebhooksApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Enroll for Webhook Notifications
   * Enrolls the customer to receive event notifications via webhooks. 
   * @param endpoint the URL to which the webhook should be sent (required)
   * @param xApiKey  (required)
   * @throws ApiException if fails to make API call
   */
  public void createWebhook(@javax.annotation.Nonnull String endpoint, @javax.annotation.Nonnull String xApiKey) throws ApiException {
    createWebhook(endpoint, xApiKey, null);
  }

  /**
   * Enroll for Webhook Notifications
   * Enrolls the customer to receive event notifications via webhooks. 
   * @param endpoint the URL to which the webhook should be sent (required)
   * @param xApiKey  (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void createWebhook(@javax.annotation.Nonnull String endpoint, @javax.annotation.Nonnull String xApiKey, Map<String, String> headers) throws ApiException {
    createWebhookWithHttpInfo(endpoint, xApiKey, headers);
  }

  /**
   * Enroll for Webhook Notifications
   * Enrolls the customer to receive event notifications via webhooks. 
   * @param endpoint the URL to which the webhook should be sent (required)
   * @param xApiKey  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> createWebhookWithHttpInfo(@javax.annotation.Nonnull String endpoint, @javax.annotation.Nonnull String xApiKey) throws ApiException {
    return createWebhookWithHttpInfo(endpoint, xApiKey, null);
  }

  /**
   * Enroll for Webhook Notifications
   * Enrolls the customer to receive event notifications via webhooks. 
   * @param endpoint the URL to which the webhook should be sent (required)
   * @param xApiKey  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> createWebhookWithHttpInfo(@javax.annotation.Nonnull String endpoint, @javax.annotation.Nonnull String xApiKey, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createWebhookRequestBuilder(endpoint, xApiKey, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createWebhook", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createWebhookRequestBuilder(@javax.annotation.Nonnull String endpoint, @javax.annotation.Nonnull String xApiKey, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'endpoint' is set
    if (endpoint == null) {
      throw new ApiException(400, "Missing the required parameter 'endpoint' when calling createWebhook");
    }
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling createWebhook");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/webhook";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "endpoint";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("endpoint", endpoint));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete Customer Webhooks
   * Deletes all registered webhook endpoints for the customer. 
   * @param xApiKey  (required)
   * @throws ApiException if fails to make API call
   */
  public void deleteWebhooks(@javax.annotation.Nonnull String xApiKey) throws ApiException {
    deleteWebhooks(xApiKey, null);
  }

  /**
   * Delete Customer Webhooks
   * Deletes all registered webhook endpoints for the customer. 
   * @param xApiKey  (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void deleteWebhooks(@javax.annotation.Nonnull String xApiKey, Map<String, String> headers) throws ApiException {
    deleteWebhooksWithHttpInfo(xApiKey, headers);
  }

  /**
   * Delete Customer Webhooks
   * Deletes all registered webhook endpoints for the customer. 
   * @param xApiKey  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteWebhooksWithHttpInfo(@javax.annotation.Nonnull String xApiKey) throws ApiException {
    return deleteWebhooksWithHttpInfo(xApiKey, null);
  }

  /**
   * Delete Customer Webhooks
   * Deletes all registered webhook endpoints for the customer. 
   * @param xApiKey  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteWebhooksWithHttpInfo(@javax.annotation.Nonnull String xApiKey, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteWebhooksRequestBuilder(xApiKey, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteWebhooks", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteWebhooksRequestBuilder(@javax.annotation.Nonnull String xApiKey, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling deleteWebhooks");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/webhook";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Retrieve Webhook Signing Key
   * Retrieves the public key used to verify signatures on incoming webhook payloads. 
   * @param id the ID of the key (required)
   * @return Key
   * @throws ApiException if fails to make API call
   */
  public Key getWebhookSigningKey(@javax.annotation.Nonnull String id) throws ApiException {
    return getWebhookSigningKey(id, null);
  }

  /**
   * Retrieve Webhook Signing Key
   * Retrieves the public key used to verify signatures on incoming webhook payloads. 
   * @param id the ID of the key (required)
   * @param headers Optional headers to include in the request
   * @return Key
   * @throws ApiException if fails to make API call
   */
  public Key getWebhookSigningKey(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    ApiResponse<Key> localVarResponse = getWebhookSigningKeyWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * Retrieve Webhook Signing Key
   * Retrieves the public key used to verify signatures on incoming webhook payloads. 
   * @param id the ID of the key (required)
   * @return ApiResponse&lt;Key&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Key> getWebhookSigningKeyWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return getWebhookSigningKeyWithHttpInfo(id, null);
  }

  /**
   * Retrieve Webhook Signing Key
   * Retrieves the public key used to verify signatures on incoming webhook payloads. 
   * @param id the ID of the key (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Key&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Key> getWebhookSigningKeyWithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getWebhookSigningKeyRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getWebhookSigningKey", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Key>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Key responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Key>() {});
        

        return new ApiResponse<Key>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getWebhookSigningKeyRequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getWebhookSigningKey");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/webhook/public-key";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("id", id));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Retrieve Webhook Batches
   * Retrieves paged webhook batches associated with the customer. The time range specified by created_after and created_before filters must not exceed 31 days. If neither is specified, the default time range is the last 3 days. Optional filters include status categories, webhook, limit and offset. 
   * @param xApiKey  (required)
   * @param createdAfter Inclusive lower bound(UTC) for filtering webhook batches by creation time. Formats: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ  (optional)
   * @param createdBefore Exclusive upper bound(UTC) for filtering webhook batches by creation time. Formats: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ  (optional)
   * @param statuses Filters webhook batches by webhook response status category. Values must be unique and encoded as a comma-separated list in the query string. If not provided, batches with all categories are returned.  (optional)
   * @param webhook Filters webhook batches by the webhook endpoint to which events in the batch were posted.  (optional)
   * @param limit The maximum number of webhook batches to return  (optional, default to 500)
   * @param offset The number of webhook batches to skip before starting to collect the result set  (optional, default to 0)
   * @return WebhookBatchResult
   * @throws ApiException if fails to make API call
   */
  public WebhookBatchResult listWebhookBatches(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String createdAfter, @javax.annotation.Nullable String createdBefore, @javax.annotation.Nullable List<String> statuses, @javax.annotation.Nullable String webhook, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset) throws ApiException {
    return listWebhookBatches(xApiKey, createdAfter, createdBefore, statuses, webhook, limit, offset, null);
  }

  /**
   * Retrieve Webhook Batches
   * Retrieves paged webhook batches associated with the customer. The time range specified by created_after and created_before filters must not exceed 31 days. If neither is specified, the default time range is the last 3 days. Optional filters include status categories, webhook, limit and offset. 
   * @param xApiKey  (required)
   * @param createdAfter Inclusive lower bound(UTC) for filtering webhook batches by creation time. Formats: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ  (optional)
   * @param createdBefore Exclusive upper bound(UTC) for filtering webhook batches by creation time. Formats: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ  (optional)
   * @param statuses Filters webhook batches by webhook response status category. Values must be unique and encoded as a comma-separated list in the query string. If not provided, batches with all categories are returned.  (optional)
   * @param webhook Filters webhook batches by the webhook endpoint to which events in the batch were posted.  (optional)
   * @param limit The maximum number of webhook batches to return  (optional, default to 500)
   * @param offset The number of webhook batches to skip before starting to collect the result set  (optional, default to 0)
   * @param headers Optional headers to include in the request
   * @return WebhookBatchResult
   * @throws ApiException if fails to make API call
   */
  public WebhookBatchResult listWebhookBatches(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String createdAfter, @javax.annotation.Nullable String createdBefore, @javax.annotation.Nullable List<String> statuses, @javax.annotation.Nullable String webhook, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, Map<String, String> headers) throws ApiException {
    ApiResponse<WebhookBatchResult> localVarResponse = listWebhookBatchesWithHttpInfo(xApiKey, createdAfter, createdBefore, statuses, webhook, limit, offset, headers);
    return localVarResponse.getData();
  }

  /**
   * Retrieve Webhook Batches
   * Retrieves paged webhook batches associated with the customer. The time range specified by created_after and created_before filters must not exceed 31 days. If neither is specified, the default time range is the last 3 days. Optional filters include status categories, webhook, limit and offset. 
   * @param xApiKey  (required)
   * @param createdAfter Inclusive lower bound(UTC) for filtering webhook batches by creation time. Formats: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ  (optional)
   * @param createdBefore Exclusive upper bound(UTC) for filtering webhook batches by creation time. Formats: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ  (optional)
   * @param statuses Filters webhook batches by webhook response status category. Values must be unique and encoded as a comma-separated list in the query string. If not provided, batches with all categories are returned.  (optional)
   * @param webhook Filters webhook batches by the webhook endpoint to which events in the batch were posted.  (optional)
   * @param limit The maximum number of webhook batches to return  (optional, default to 500)
   * @param offset The number of webhook batches to skip before starting to collect the result set  (optional, default to 0)
   * @return ApiResponse&lt;WebhookBatchResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<WebhookBatchResult> listWebhookBatchesWithHttpInfo(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String createdAfter, @javax.annotation.Nullable String createdBefore, @javax.annotation.Nullable List<String> statuses, @javax.annotation.Nullable String webhook, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset) throws ApiException {
    return listWebhookBatchesWithHttpInfo(xApiKey, createdAfter, createdBefore, statuses, webhook, limit, offset, null);
  }

  /**
   * Retrieve Webhook Batches
   * Retrieves paged webhook batches associated with the customer. The time range specified by created_after and created_before filters must not exceed 31 days. If neither is specified, the default time range is the last 3 days. Optional filters include status categories, webhook, limit and offset. 
   * @param xApiKey  (required)
   * @param createdAfter Inclusive lower bound(UTC) for filtering webhook batches by creation time. Formats: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ  (optional)
   * @param createdBefore Exclusive upper bound(UTC) for filtering webhook batches by creation time. Formats: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ  (optional)
   * @param statuses Filters webhook batches by webhook response status category. Values must be unique and encoded as a comma-separated list in the query string. If not provided, batches with all categories are returned.  (optional)
   * @param webhook Filters webhook batches by the webhook endpoint to which events in the batch were posted.  (optional)
   * @param limit The maximum number of webhook batches to return  (optional, default to 500)
   * @param offset The number of webhook batches to skip before starting to collect the result set  (optional, default to 0)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;WebhookBatchResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<WebhookBatchResult> listWebhookBatchesWithHttpInfo(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String createdAfter, @javax.annotation.Nullable String createdBefore, @javax.annotation.Nullable List<String> statuses, @javax.annotation.Nullable String webhook, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listWebhookBatchesRequestBuilder(xApiKey, createdAfter, createdBefore, statuses, webhook, limit, offset, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listWebhookBatches", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<WebhookBatchResult>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        WebhookBatchResult responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<WebhookBatchResult>() {});
        

        return new ApiResponse<WebhookBatchResult>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listWebhookBatchesRequestBuilder(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable String createdAfter, @javax.annotation.Nullable String createdBefore, @javax.annotation.Nullable List<String> statuses, @javax.annotation.Nullable String webhook, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling listWebhookBatches");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/webhook-batch";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "created_after";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("created_after", createdAfter));
    localVarQueryParameterBaseName = "created_before";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("created_before", createdBefore));
    localVarQueryParameterBaseName = "statuses";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "statuses", statuses));
    localVarQueryParameterBaseName = "webhook";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("webhook", webhook));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "offset";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("offset", offset));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Retrieve Customer Webhooks
   * Retrieves all registered webhook endpoints associated with the customer. 
   * @param xApiKey  (required)
   * @return List&lt;Webhook&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Webhook> listWebhooks(@javax.annotation.Nonnull String xApiKey) throws ApiException {
    return listWebhooks(xApiKey, null);
  }

  /**
   * Retrieve Customer Webhooks
   * Retrieves all registered webhook endpoints associated with the customer. 
   * @param xApiKey  (required)
   * @param headers Optional headers to include in the request
   * @return List&lt;Webhook&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Webhook> listWebhooks(@javax.annotation.Nonnull String xApiKey, Map<String, String> headers) throws ApiException {
    ApiResponse<List<Webhook>> localVarResponse = listWebhooksWithHttpInfo(xApiKey, headers);
    return localVarResponse.getData();
  }

  /**
   * Retrieve Customer Webhooks
   * Retrieves all registered webhook endpoints associated with the customer. 
   * @param xApiKey  (required)
   * @return ApiResponse&lt;List&lt;Webhook&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Webhook>> listWebhooksWithHttpInfo(@javax.annotation.Nonnull String xApiKey) throws ApiException {
    return listWebhooksWithHttpInfo(xApiKey, null);
  }

  /**
   * Retrieve Customer Webhooks
   * Retrieves all registered webhook endpoints associated with the customer. 
   * @param xApiKey  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;Webhook&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Webhook>> listWebhooksWithHttpInfo(@javax.annotation.Nonnull String xApiKey, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listWebhooksRequestBuilder(xApiKey, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listWebhooks", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<Webhook>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<Webhook> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<Webhook>>() {});
        

        return new ApiResponse<List<Webhook>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listWebhooksRequestBuilder(@javax.annotation.Nonnull String xApiKey, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling listWebhooks");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/webhook";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Resend Events
   * Synchronously resend the webhook batch with the provided batch_id for the customer. The result is returned in the response. 
   * @param batchId the ID of the batch (required)
   * @param xApiKey  (required)
   * @return WebhookResendResponse
   * @throws ApiException if fails to make API call
   */
  public WebhookResendResponse resendWebhookBatch(@javax.annotation.Nonnull Long batchId, @javax.annotation.Nonnull String xApiKey) throws ApiException {
    return resendWebhookBatch(batchId, xApiKey, null);
  }

  /**
   * Resend Events
   * Synchronously resend the webhook batch with the provided batch_id for the customer. The result is returned in the response. 
   * @param batchId the ID of the batch (required)
   * @param xApiKey  (required)
   * @param headers Optional headers to include in the request
   * @return WebhookResendResponse
   * @throws ApiException if fails to make API call
   */
  public WebhookResendResponse resendWebhookBatch(@javax.annotation.Nonnull Long batchId, @javax.annotation.Nonnull String xApiKey, Map<String, String> headers) throws ApiException {
    ApiResponse<WebhookResendResponse> localVarResponse = resendWebhookBatchWithHttpInfo(batchId, xApiKey, headers);
    return localVarResponse.getData();
  }

  /**
   * Resend Events
   * Synchronously resend the webhook batch with the provided batch_id for the customer. The result is returned in the response. 
   * @param batchId the ID of the batch (required)
   * @param xApiKey  (required)
   * @return ApiResponse&lt;WebhookResendResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<WebhookResendResponse> resendWebhookBatchWithHttpInfo(@javax.annotation.Nonnull Long batchId, @javax.annotation.Nonnull String xApiKey) throws ApiException {
    return resendWebhookBatchWithHttpInfo(batchId, xApiKey, null);
  }

  /**
   * Resend Events
   * Synchronously resend the webhook batch with the provided batch_id for the customer. The result is returned in the response. 
   * @param batchId the ID of the batch (required)
   * @param xApiKey  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;WebhookResendResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<WebhookResendResponse> resendWebhookBatchWithHttpInfo(@javax.annotation.Nonnull Long batchId, @javax.annotation.Nonnull String xApiKey, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = resendWebhookBatchRequestBuilder(batchId, xApiKey, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("resendWebhookBatch", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<WebhookResendResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        WebhookResendResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<WebhookResendResponse>() {});
        

        return new ApiResponse<WebhookResendResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder resendWebhookBatchRequestBuilder(@javax.annotation.Nonnull Long batchId, @javax.annotation.Nonnull String xApiKey, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'batchId' is set
    if (batchId == null) {
      throw new ApiException(400, "Missing the required parameter 'batchId' when calling resendWebhookBatch");
    }
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling resendWebhookBatch");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/webhook-batch/{batch_id}/resend"
        .replace("{batch_id}", ApiClient.urlEncode(batchId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Validate Enrolled Webhook
   * Validates whether your enrolled webhook(s) respond with an HTTP 2xx status code. Sends a test request to each webhook containing your customer handle, a hardcoded event type(test), a hardcoded sender email(test@mailchannels.com),a timestamp, a request ID (provided or generated), and an SMTP ID. The response includes the HTTP status code and body returned by each webhook. 
   * @param xApiKey  (required)
   * @param webhookValidationRequestBody  (optional)
   * @return WebhookValidationResults
   * @throws ApiException if fails to make API call
   */
  public WebhookValidationResults validateWebhook(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable WebhookValidationRequestBody webhookValidationRequestBody) throws ApiException {
    return validateWebhook(xApiKey, webhookValidationRequestBody, null);
  }

  /**
   * Validate Enrolled Webhook
   * Validates whether your enrolled webhook(s) respond with an HTTP 2xx status code. Sends a test request to each webhook containing your customer handle, a hardcoded event type(test), a hardcoded sender email(test@mailchannels.com),a timestamp, a request ID (provided or generated), and an SMTP ID. The response includes the HTTP status code and body returned by each webhook. 
   * @param xApiKey  (required)
   * @param webhookValidationRequestBody  (optional)
   * @param headers Optional headers to include in the request
   * @return WebhookValidationResults
   * @throws ApiException if fails to make API call
   */
  public WebhookValidationResults validateWebhook(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable WebhookValidationRequestBody webhookValidationRequestBody, Map<String, String> headers) throws ApiException {
    ApiResponse<WebhookValidationResults> localVarResponse = validateWebhookWithHttpInfo(xApiKey, webhookValidationRequestBody, headers);
    return localVarResponse.getData();
  }

  /**
   * Validate Enrolled Webhook
   * Validates whether your enrolled webhook(s) respond with an HTTP 2xx status code. Sends a test request to each webhook containing your customer handle, a hardcoded event type(test), a hardcoded sender email(test@mailchannels.com),a timestamp, a request ID (provided or generated), and an SMTP ID. The response includes the HTTP status code and body returned by each webhook. 
   * @param xApiKey  (required)
   * @param webhookValidationRequestBody  (optional)
   * @return ApiResponse&lt;WebhookValidationResults&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<WebhookValidationResults> validateWebhookWithHttpInfo(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable WebhookValidationRequestBody webhookValidationRequestBody) throws ApiException {
    return validateWebhookWithHttpInfo(xApiKey, webhookValidationRequestBody, null);
  }

  /**
   * Validate Enrolled Webhook
   * Validates whether your enrolled webhook(s) respond with an HTTP 2xx status code. Sends a test request to each webhook containing your customer handle, a hardcoded event type(test), a hardcoded sender email(test@mailchannels.com),a timestamp, a request ID (provided or generated), and an SMTP ID. The response includes the HTTP status code and body returned by each webhook. 
   * @param xApiKey  (required)
   * @param webhookValidationRequestBody  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;WebhookValidationResults&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<WebhookValidationResults> validateWebhookWithHttpInfo(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable WebhookValidationRequestBody webhookValidationRequestBody, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = validateWebhookRequestBuilder(xApiKey, webhookValidationRequestBody, headers);
    try {
      HttpResponse<InputStream> localVarResponse = com.mailchannels.client.BoundedHttpTransport.send(
          memberVarHttpClient, localVarRequestBuilder.build());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("validateWebhook", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<WebhookValidationResults>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        WebhookValidationResults responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<WebhookValidationResults>() {});
        

        return new ApiResponse<WebhookValidationResults>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder validateWebhookRequestBuilder(@javax.annotation.Nonnull String xApiKey, @javax.annotation.Nullable WebhookValidationRequestBody webhookValidationRequestBody, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'xApiKey' is set
    if (xApiKey == null) {
      throw new ApiException(400, "Missing the required parameter 'xApiKey' when calling validateWebhook");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/webhook/validate";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiKey != null) {
      localVarRequestBuilder.header("X-Api-Key", xApiKey.toString());
    }
    if (webhookValidationRequestBody != null) localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      if (webhookValidationRequestBody == null) {
        localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
      } else {
        byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(webhookValidationRequestBody);
        localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
